"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useId, useMemo, useRef, useState } from "react";
import { Heart, Search, X } from "lucide-react";
import type { FootballSearchData } from "@/domain/football/types";
import { LeagueMark } from "@/features/football/components/league-mark";
import { TeamCrest } from "@/features/football/components/team-crest";
const links = [["/matches", "Matches"], ["/live", "Live"], ["/leagues", "Leagues"]] as const;
const emptyData: FootballSearchData = { clubs: [], matches: [], competitions: [] };

export function AppHeader() {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null);
  const close = () => { setOpen(false); requestAnimationFrame(() => trigger.current?.focus()); };
  return <><header className="sticky top-0 z-50 border-b border-white/[.07] bg-[#080a0d]/92 backdrop-blur-xl"><div className="page-shell flex h-18 items-center gap-7"><Link href="/" aria-label="NINETY home" className="text-xl font-black tracking-[-.08em]">NINETY<span className="text-[var(--lime)]">.</span></Link><nav className="hidden gap-6 text-sm font-semibold md:flex" aria-label="Primary">{links.map(([href, label]) => <Link key={href} href={href} aria-current={pathname.startsWith(href) ? "page" : undefined} className={pathname.startsWith(href) ? "text-white" : "text-[#8d949d] hover:text-white"}>{label}</Link>)}</nav><div className="ml-auto flex gap-1"><button ref={trigger} type="button" onClick={() => setOpen(true)} aria-label="Search football" aria-haspopup="dialog" className="grid h-11 w-11 place-items-center rounded-full text-[#9ba2aa] hover:bg-white/[.06] hover:text-white"><Search size={19}/></button><Link href="/favorites" aria-label="Favorite clubs" aria-current={pathname === "/favorites" ? "page" : undefined} className={`grid h-11 w-11 place-items-center rounded-full ${pathname === "/favorites" ? "text-[var(--lime)]" : "text-[#9ba2aa] hover:bg-white/[.06] hover:text-white"}`}><Heart size={19}/></Link></div></div><nav className="hide-scrollbar flex justify-around border-t border-white/[.05] px-2 md:hidden" aria-label="Mobile navigation">{[["/", "Home"], ["/live", "Live"], ["/matches", "Matches"], ["/favorites", "Favorites"]].map(([href, label]) => <Link key={href} href={href} aria-current={pathname === href ? "page" : undefined} className={`min-h-12 min-w-18 py-3 text-center text-xs font-semibold ${pathname === href ? "text-[var(--lime)]" : "text-[#8d949d]"}`}>{label}</Link>)}</nav></header>{open && <SearchDialog close={close}/>}</>;
}

function SearchDialog({ close }: { close: () => void }) {
  const [query, setQuery] = useState(""); const [data, setData] = useState<FootballSearchData>(emptyData); const [loading, setLoading] = useState(false); const [active, setActive] = useState(0); const input = useRef<HTMLInputElement>(null); const dialog = useRef<HTMLDivElement>(null); const router = useRouter(); const listId = useId();
  const results = useMemo(() => query.trim().length < 2 ? [] : [...data.clubs.map((club) => ({ id: club.id, label: <span className="flex min-w-0 items-center gap-3"><TeamCrest team={club} size="small"/><span className="truncate">{club.name}</span></span>, meta: "Club", href: `/club/${club.slug}`, group: "Clubs" })), ...data.matches.map((match) => ({ id: match.id, label: <span className="flex min-w-0 items-center gap-3"><span className="flex shrink-0 -space-x-2"><TeamCrest team={match.home} size="small"/><TeamCrest team={match.away} size="small"/></span><span className="truncate">{match.home.name} vs {match.away.name}</span></span>, meta: match.status, href: `/watch/${match.id}`, group: "Matches" })), ...data.competitions.map((competition) => ({ id: competition.id, label: <span className="flex min-w-0 items-center gap-3"><LeagueMark slug={competition.slug} name={competition.name} size="small" showFallbackLabel/><span className="truncate">{competition.name}</span></span>, meta: competition.region ?? "Football", href: `/league/${competition.slug}`, group: "Competitions" }))], [data, query]);
  useEffect(() => { input.current?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key === "Tab" && dialog.current) { const focusable = [...dialog.current.querySelectorAll<HTMLElement>('button,input,[href]')]; const first = focusable[0], last = focusable.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [close]);
  useEffect(() => { const term = query.trim(); if (term.length < 2) return; const controller = new AbortController(); const timer = setTimeout(async () => { setLoading(true); try { const response = await fetch(`/api/football/search?q=${encodeURIComponent(term)}`, { signal: controller.signal }); setData(response.ok ? await response.json() : emptyData); } catch { if (!controller.signal.aborted) setData(emptyData); } finally { if (!controller.signal.aborted) setLoading(false); } }, 220); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  const go = (href: string) => { close(); router.push(href); }; const empty = query.trim().length >= 2 && !loading && !results.length;
  const keyDown = (event: React.KeyboardEvent<HTMLInputElement>) => { if (event.key === "ArrowDown") { event.preventDefault(); setActive((value) => Math.min(value + 1, Math.max(0, results.length - 1))); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((value) => Math.max(0, value - 1)); } if (event.key === "Enter" && results[active]) { event.preventDefault(); go(results[active].href); } };
  return <div className="fixed inset-0 z-[100] bg-black/80 p-0 backdrop-blur-md sm:p-3" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby={`${listId}-title`} className="mx-auto flex h-dvh max-w-2xl flex-col overflow-hidden bg-[#111419] shadow-2xl sm:mt-[8vh] sm:h-auto sm:max-h-[78vh] sm:rounded-3xl sm:border sm:border-white/10"><h2 id={`${listId}-title`} className="sr-only">Search football</h2><div className="flex items-center gap-3 border-b border-white/[.08] px-4 sm:px-5"><Search size={20} className="text-[#7f8790]"/><input ref={input} value={query} maxLength={80} onChange={(event) => setQuery(event.target.value)} onKeyDown={keyDown} role="combobox" aria-expanded={results.length > 0} aria-controls={listId} aria-activedescendant={results[active] ? `${listId}-${active}` : undefined} aria-autocomplete="list" placeholder="Search clubs, matches, competitions…" className="h-16 min-w-0 flex-1 bg-transparent text-base outline-none placeholder:text-[#69717a]"/><button type="button" onClick={close} aria-label="Close search" className="grid h-11 w-11 place-items-center rounded-full hover:bg-white/[.06]"><X size={20}/></button></div><div id={listId} role="listbox" aria-label="Search results" className="flex-1 overflow-y-auto p-3" aria-busy={loading}>{results.map((result, index) => <div key={`${result.group}-${result.id}`}>{index === 0 || results[index - 1].group !== result.group ? <h3 className="px-3 pb-2 pt-3 text-[10px] font-bold uppercase tracking-[.18em] text-[#747c85]">{result.group}</h3> : null}<button id={`${listId}-${index}`} role="option" aria-selected={active === index} type="button" onMouseEnter={() => setActive(index)} onClick={() => go(result.href)} className={`flex min-h-12 w-full items-center justify-between gap-4 rounded-xl px-3 py-3 text-left ${active === index ? "bg-white/[.07]" : "hover:bg-white/[.05]"}`}><span className="min-w-0 truncate font-semibold">{result.label}</span><span className="shrink-0 text-xs text-[#858d96]">{result.meta}</span></button></div>)}{loading && <p role="status" className="py-12 text-center text-sm text-[#8d949d]">Searching football…</p>}{empty && <p role="status" className="py-12 text-center text-sm text-[#8d949d]">No football results found.</p>}{query.trim().length < 2 && <p className="py-12 text-center text-sm text-[#8d949d]">Type at least two characters to search NINETY.</p>}</div></div></div>;
}
