"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { Heart, Search, X } from "lucide-react";
import type { FootballSearchData } from "@/domain/football/types";

const links = [["/matches","Matches"],["/live","Live"],["/leagues","Leagues"]] as const;
export function AppHeader() { const pathname = usePathname(); const [open,setOpen] = useState(false); return <><header className="sticky top-0 z-50 border-b border-white/[.07] bg-[#080a0d]/92 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-[1500px] items-center gap-7 px-5 sm:px-8"><Link href="/" className="text-xl font-black tracking-[-.08em]">NINETY<span className="text-[#c7ff4a]">.</span></Link><nav className="hidden gap-6 text-sm font-semibold md:flex" aria-label="Primary">{links.map(([href,label]) => <Link key={href} href={href} className={pathname.startsWith(href) ? "text-white" : "text-[#7d848d] hover:text-white"}>{label}</Link>)}</nav><div className="ml-auto flex gap-1"><button onClick={() => setOpen(true)} aria-label="Search football" className="grid h-11 w-11 place-items-center rounded-full text-[#8d949d] hover:bg-white/[.05] hover:text-white"><Search size={19}/></button><Link href="/favorites" aria-label="Favorites" className={`grid h-11 w-11 place-items-center rounded-full ${pathname === "/favorites" ? "text-[#c7ff4a]" : "text-[#8d949d]"}`}><Heart size={19}/></Link></div></div><nav className="hide-scrollbar flex justify-around border-t border-white/[.05] px-2 md:hidden" aria-label="Mobile navigation">{[["/","Home"],["/live","Live"],["/matches","Matches"],["/favorites","Favorites"]].map(([href,label]) => <Link key={href} href={href} className={`min-w-18 py-3 text-center text-xs font-semibold ${pathname === href ? "text-[#c7ff4a]" : "text-[#7d848d]"}`}>{label}</Link>)}</nav></header>{open && <SearchDialog close={() => setOpen(false)}/>}</>; }

function SearchDialog({ close }: { close: () => void }) { const [query,setQuery] = useState(""); const [data,setData] = useState<FootballSearchData>({ clubs:[],matches:[],competitions:[] }); const input = useRef<HTMLInputElement>(null); const router = useRouter(); useEffect(() => { input.current?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; window.addEventListener("keydown",handler); return () => window.removeEventListener("keydown",handler); }, [close]); useEffect(() => { if (query.trim().length < 2) return; const controller = new AbortController(); const timer = setTimeout(() => { fetch(`/api/football/search?q=${encodeURIComponent(query)}`,{signal:controller.signal}).then((response) => response.json()).then(setData).catch(() => {}); },250); return () => { clearTimeout(timer); controller.abort(); }; },[query]); const visible=query.length<2?{clubs:[],matches:[],competitions:[]}:data; const go=(href:string)=>{close();router.push(href);}; const empty=query.length>=2&&!visible.clubs.length&&!visible.matches.length&&!visible.competitions.length; return <div className="fixed inset-0 z-[100] bg-black/75 p-3 backdrop-blur-md" role="dialog" aria-modal="true" aria-label="Search football" onMouseDown={(e)=>{if(e.target===e.currentTarget)close();}}><div className="mx-auto mt-[8vh] max-w-2xl overflow-hidden rounded-3xl border border-white/10 bg-[#111419] shadow-2xl"><div className="flex items-center gap-3 border-b border-white/[.08] px-5"><Search size={20} className="text-[#737a83]"/><input ref={input} value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search clubs, matches, competitions…" className="h-16 flex-1 bg-transparent text-base outline-none placeholder:text-[#5f666e]"/><button onClick={close} aria-label="Close search"><X size={20}/></button></div><div className="max-h-[65vh] overflow-y-auto p-3">{visible.clubs.length>0&&<ResultGroup title="Clubs">{visible.clubs.map((club)=><Result key={club.id} label={club.name} meta="Club" onClick={()=>go(`/club/${club.slug}`)}/>)}</ResultGroup>}{visible.matches.length>0&&<ResultGroup title="Matches">{visible.matches.map((match)=><Result key={match.id} label={`${match.home.name} vs ${match.away.name}`} meta={match.status} onClick={()=>go(`/watch/${match.id}`)}/>)}</ResultGroup>}{visible.competitions.length>0&&<ResultGroup title="Competitions">{visible.competitions.map((competition)=><Result key={competition.id} label={competition.name} meta={competition.region??"Football"} onClick={()=>go(`/league/${competition.slug}`)}/>)}</ResultGroup>}{empty&&<p className="py-12 text-center text-sm text-[#7d848d]">No football results found.</p>}{query.length<2&&<p className="py-12 text-center text-sm text-[#7d848d]">Type at least two characters to search NINETY.</p>}</div></div></div>; }
function ResultGroup({title,children}:{title:string;children:React.ReactNode}){return <section className="mb-4"><h2 className="px-3 py-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#69717a]">{title}</h2>{children}</section>}
function Result({label,meta,onClick}:{label:string;meta:string;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center justify-between rounded-xl px-3 py-3 text-left hover:bg-white/[.05] focus-visible:outline-2 focus-visible:outline-[#c7ff4a]"><span className="font-semibold">{label}</span><span className="text-xs text-[#777f88]">{meta}</span></button>}
