import Link from "next/link";
import type { ClubData, Competition, Match } from "@/domain/football/types";
import { MatchCard } from "@/features/football/components/match-card";
import { TeamCrest } from "@/features/football/components/team-crest";
import { LocalKickoff } from "@/features/football/components/local-kickoff";

export function PageIntro({ eyebrow, title, detail }: { eyebrow?: string; title: string; detail?: string }) { return <div className="mb-8">{eyebrow&&<p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-[#c7ff4a]">{eyebrow}</p>}<h1 className="text-3xl font-semibold tracking-[-.05em] sm:text-5xl">{title}</h1>{detail&&<p className="mt-3 text-sm text-[#818891]">{detail}</p>}</div>; }
export function CompetitionChips({ competitions, active, base }: { competitions: Competition[]; active?: string; base: string }) { return <div className="hide-scrollbar mb-8 flex gap-2 overflow-x-auto pb-1"><Link href={base} className={`min-w-fit rounded-full border px-4 py-2 text-xs font-semibold ${!active?"border-white/20 bg-white text-black":"border-white/10 text-[#9299a1]"}`}>All</Link>{competitions.map((competition)=><Link key={competition.id} href={`${base}${base.includes("?")?"&":"?"}competition=${competition.slug}`} className={`min-w-fit rounded-full border px-4 py-2 text-xs font-semibold ${active===competition.slug?"border-[#c7ff4a]/40 bg-[#c7ff4a]/10 text-[#c7ff4a]":"border-white/10 text-[#9299a1]"}`}>{competition.name}</Link>)}</div>; }
export function MatchGrid({ matches }: { matches: Match[] }) { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{matches.map((match)=><div className="min-w-0" key={match.id}><MatchCard match={match}/></div>)}</div>; }
export function EmptyState({ title, copy }: { title: string; copy: string }) { return <div className="grid min-h-64 place-items-center rounded-3xl border border-dashed border-white/10 bg-white/[.015] px-6 text-center"><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-2 text-sm text-[#7d848d]">{copy}</p></div></div>; }
export function ClubCard({ club }: { club: ClubData }) { const next=club.live[0]??club.upcoming[0]; return <Link href={`/club/${club.team.slug}`} className="flex items-center gap-4 rounded-2xl border border-white/[.07] bg-[#111419] p-5 outline-none hover:border-white/15 focus-visible:ring-2 focus-visible:ring-[#c7ff4a]"><TeamCrest team={club.team} size="medium"/><div className="min-w-0 flex-1"><h2 className="truncate font-semibold">{club.team.name}</h2>{next?<p className="mt-1 truncate text-xs text-[#7d848d]">{next.status==="LIVE"?"Live now":<><LocalKickoff kickoff={next.kickoff}/> · </>} {next.home.slug===club.team.slug?`vs ${next.away.name}`:`at ${next.home.name}`}</p>:<p className="mt-1 text-xs text-[#7d848d]">No upcoming fixture</p>}</div></Link>; }
export function DiscoveryLoading() { return <div className="min-h-screen"><div className="h-24 border-b border-white/[.06] bg-white/[.02]"/><main className="mx-auto max-w-[1500px] px-5 py-12 sm:px-8"><div className="h-5 w-28 animate-pulse rounded bg-white/[.05]"/><div className="mt-4 h-12 w-80 max-w-full animate-pulse rounded bg-white/[.05]"/><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map((item)=><div key={item} className="h-52 animate-pulse rounded-2xl bg-white/[.04]"/>)}</div></main></div>; }
