/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 52b779d76a9b8d6f28826ae38f0b1447)
interface __BaseEnv_CloudflareEnv {
	SEARCH_RATE_LIMITER: RateLimit;
	METADATA_RATE_LIMITER: RateLimit;
	PLAYBACK_RATE_LIMITER: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	FOOTBALL_PROVIDER: string;
	FOOTBALL_PROVIDER_BASE_URL: string;
	FOOTBALL_STREAM_PROVIDER: string;
	FOOTBALL_STREAM_CATALOG_JSON: string;
	FOOTBALL_EMBED_ORIGINS: string;
	NINETY_SITE_URL: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FOOTBALL_PROVIDER" | "FOOTBALL_PROVIDER_BASE_URL" | "FOOTBALL_STREAM_PROVIDER" | "FOOTBALL_STREAM_CATALOG_JSON" | "FOOTBALL_EMBED_ORIGINS" | "NINETY_SITE_URL">> {}
}
