"use client";
import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
type MatchEvent={minute:number|null;extra:number|null;team:string;player:string;assist:string;type:string;detail:string};
type Details={status:'available'|'unavailable';checkedAt?:number;message?:string;events?:MatchEvent[]};
export function MatchEvents({home,away,date,ended}:{home:string;away:string;date:number;ended:boolean}){
  const [data,setData]=useState<Details|null>(null),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0);
  useEffect(()=>{let cancelled=false;const load=async()=>{if(document.hidden)return;setLoading(true);try{const response=await fetch('/api/match-details?'+new URLSearchParams({home,away,date:String(date)}));if(!response.ok)throw new Error();const result=await response.json() as Details;if(!cancelled)setData(result);}catch{if(!cancelled)setData({status:'unavailable',message:'Match events are temporarily unavailable.'});}finally{if(!cancelled)setLoading(false);}};void load();const timer=ended?undefined:window.setInterval(()=>void load(),300000);return()=>{cancelled=true;if(timer)clearInterval(timer);};},[home,away,date,ended,retry]);
  return <section id="events-panel" role="tabpanel" aria-labelledby="events-tab" className="match-events-panel"><div className="match-events-heading"><div><h2>Match timeline</h2><p>{data?.checkedAt?'Provider data checked '+new Date(data.checkedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'Reported goals, cards and substitutions'}</p></div><button disabled={loading} onClick={()=>setRetry(x=>x+1)}><RefreshCw size={15}/>{loading?'Checking…':'Refresh'}</button></div>{data?.status==='available'&&data.events?.length?<ol>{data.events.map((event,index)=><li key={index}><time>{event.minute??'—'}{event.extra?'+'+event.extra:''}′</time><div><strong>{event.type==='subst'?'Substitution':event.detail||event.type}</strong><span>{event.player}{event.assist?(event.type==='subst'?' → ':' · Assist: ')+event.assist:''}</span><small>{event.team}</small></div></li>)}</ol>:<p className="match-events-empty">{!data?'Checking provider reports…':data.message??'No match events have been reported by the connected provider yet.'}</p>}<small className="match-events-credit">API-Football reports · Coverage and updates depend on the connected plan.</small></section>;
}
