"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, Shield, UserPlus, RefreshCw } from "lucide-react";
type Friend={id:string;username:string;enabled:number;created:number;lastLogin:number|null};
type Health={day:string;category:string;count:number};
type HealthSummary={windowDays:number;total:number;totals:Record<string,number>;status:"healthy"|"attention"};
export default function AdminPage(){
  const [services,setServices]=useState<{accounts:boolean;footballData:boolean}|null>(null),[healthSummary,setHealthSummary]=useState<HealthSummary|null>(null),[observedAt,setObservedAt]=useState<string|null>(null);
  const [friends,setFriends]=useState<Friend[]>([]),[health,setHealth]=useState<Health[]>([]),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[resetId,setResetId]=useState<string|null>(null),[resetPassword,setResetPassword]=useState('');
  const load=async()=>{const response=await fetch('/api/admin/accounts',{cache:'no-store'});const data=await response.json() as {accounts?:Friend[];health?:Health[];healthSummary?:HealthSummary;observedAt?:string;services?:{accounts:boolean;footballData:boolean};error?:string};if(!response.ok)throw new Error(data.error??'Dashboard unavailable');setFriends(data.accounts??[]);setHealth(data.health??[]);setHealthSummary(data.healthSummary??null);setObservedAt(data.observedAt??null);setServices(data.services??null);};
  useEffect(()=>{void load().catch(error=>setMessage(error.message));},[]);
  const mutate=async(path:string,body:object)=>{setBusy(true);setMessage('');try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error??'Request failed');await load();setMessage('Changes saved.');return true;}catch(error){setMessage((error as Error).message);return false;}finally{setBusy(false);}};
  return <main className="admin-page"><header><a href="/"><ArrowLeft size={17}/>Back to matches</a><span><Shield size={18}/>Owner dashboard</span></header><div className="admin-intro"><span className="eyebrow">PRIVATE MATCHDAY</span><h1>Your circle. Your control.</h1><p>Create a separate login for each friend. Disabling an account or resetting its password signs it out.</p></div>
    <section className="admin-card"><h2><UserPlus size={21}/>Invite a friend</h2><form onSubmit={async event=>{event.preventDefault();if(await mutate('/api/admin/accounts',{username,password})){setUsername('');setPassword('');}}}><label>Username<input required pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,39}" maxLength={40} value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off"/></label><label>Initial password<input required type="password" minLength={12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><button disabled={busy}>Create account</button></form><p>Share the username and password privately. Friends sign in on the existing login page.</p></section>
    {message&&<p className="admin-message" role="status">{message}</p>}
    <section className="admin-card"><div className="admin-section-heading"><h2>Friend accounts <small>{friends.length}</small></h2><button disabled={busy} onClick={()=>void load().catch(error=>setMessage(error.message))} aria-label="Refresh dashboard"><RefreshCw size={17}/></button></div>{!friends.length?<p>No individual friend accounts yet. Your existing guest login continues to work.</p>:<div className="admin-accounts">{friends.map(friend=><article key={friend.id}><div><strong>{friend.username}</strong><span>{friend.enabled?'Active':'Disabled'} · {friend.lastLogin?'Last sign-in '+new Date(friend.lastLogin).toLocaleDateString():'Has not signed in yet'}</span></div><div><button disabled={busy} onClick={()=>void mutate('/api/admin/account',{id:friend.id,enabled:!friend.enabled})}>{friend.enabled?'Disable':'Enable'}</button><button disabled={busy} onClick={()=>{setResetId(friend.id);setResetPassword('');}}>Reset password</button></div>{resetId===friend.id&&<form className="password-reset" onSubmit={async event=>{event.preventDefault();if(await mutate('/api/admin/account',{id:friend.id,password:resetPassword})){setResetId(null);setResetPassword('');}}}><label>New password<input type="password" required minLength={12} maxLength={200} value={resetPassword} onChange={e=>setResetPassword(e.target.value)} autoComplete="new-password"/></label><button disabled={busy}>Save password</button><button type="button" onClick={()=>setResetId(null)}>Cancel</button></form>}</article>)}</div>}</section>
    <section className="admin-card"><h2>Service health · past 7 days</h2>{healthSummary&&<div className="service-connections"><span>Health · {healthSummary.status==="healthy"?"Healthy":"Attention"}</span><span>Recorded issues · {healthSummary.total}</span><span>Window · {healthSummary.windowDays} days</span>{observedAt&&<span>Snapshot · {new Date(observedAt).toLocaleString()}</span>}</div>}{services&&<div className="service-connections"><span>Account storage · {services.accounts?"Connected":"Unavailable"}</span><span>Match data · {services.footballData?"Key configured":"Key not configured"}</span></div>}<p>Aggregate API failures, empty source responses and reported source retries. These do not measure video playback or prove a broadcast is broken.</p>{health.length?<div className="admin-health">{health.map(row=><div key={row.day+row.category}><span>{row.category.replaceAll('-',' ')}</span><time>{row.day} UTC</time><strong>{row.count}</strong></div>)}</div>:<p>No recorded service issues.</p>}</section></main>;
}
