"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, Shield, UserPlus, RefreshCw } from "lucide-react";
type Friend={id:string;username:string;enabled:number;created:number;lastLogin:number|null};
type Health={day:string;category:string;count:number};
type TelemetryEvent={id:string;account:string;event:string;detail:string|null;created:number};
export default function AdminPage(){
  const [events,setEvents]=useState<TelemetryEvent[]>([]);
  const now=Date.now();
  const liveCutoff=now-90_000;
  const activeByAccount=new Map<string,TelemetryEvent>();
  for(const event of events){if(event.created<liveCutoff)continue;if(!activeByAccount.has(event.account))activeByAccount.set(event.account,event);}
  const watchingByAccount=new Map<string,TelemetryEvent>();
  for(const event of events){if(event.created<liveCutoff||event.event!=="session-active")continue;if(!watchingByAccount.has(event.account))watchingByAccount.set(event.account,event);}
  const activeAccounts=activeByAccount.size;
  const watchingAccounts=watchingByAccount.size;
  const matchesWatching=new Set(Array.from(watchingByAccount.values()).map(event=>{try{const detail=event.detail?JSON.parse(event.detail):{};return typeof detail.matchId==="string"?detail.matchId:"";}catch{return "";}}).filter(Boolean)).size;
  const label=(account:string)=>account.startsWith("friend:")?"friend":account.split(":")[0];
  const [services,setServices]=useState<{accounts:boolean;footballData:boolean}|null>(null);
  const [friends,setFriends]=useState<Friend[]>([]),[health,setHealth]=useState<Health[]>([]),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[resetId,setResetId]=useState<string|null>(null),[resetPassword,setResetPassword]=useState('');
  const load=async()=>{const response=await fetch('/api/admin/accounts',{cache:'no-store'});const data=await response.json() as {accounts?:Friend[];health?:Health[];services?:{accounts:boolean;footballData:boolean};error?:string};if(!response.ok)throw new Error(data.error??'Dashboard unavailable');setFriends(data.accounts??[]);setHealth(data.health??[]);setServices(data.services??null);};
  useEffect(()=>{void load().catch(error=>setMessage(error.message));void fetch('/api/admin/telemetry',{cache:'no-store'}).then(async response=>{const data=await response.json() as {events?:TelemetryEvent[]};if(response.ok)setEvents(data.events??[]);}).catch(()=>{});},[]);
  const mutate=async(path:string,body:object)=>{setBusy(true);setMessage('');try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error??'Request failed');await load();setMessage('Changes saved.');return true;}catch(error){setMessage((error as Error).message);return false;}finally{setBusy(false);}};
  return <main className="admin-page"><header><a href="/"><ArrowLeft size={17}/>Back to matches</a><span><Shield size={18}/>Owner dashboard</span></header><div className="admin-intro"><span className="eyebrow">PRIVATE MATCHDAY</span><h1>Your circle. Your control.</h1><p>Create a separate login for each friend. Disabling an account or resetting its password signs it out.</p></div>
    <section className="admin-card"><h2><UserPlus size={21}/>Invite a friend</h2><form onSubmit={async event=>{event.preventDefault();if(await mutate('/api/admin/accounts',{username,password})){setUsername('');setPassword('');}}}><label>Username<input required pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,39}" maxLength={40} value={username} onChange={e=>setUsername(e.target.value)} autoComplete="off"/></label><label>Initial password<input required type="password" minLength={12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><button disabled={busy}>Create account</button></form><p>Share the username and password privately. Friends sign in on the existing login page.</p></section>
    {message&&<p className="admin-message" role="status">{message}</p>}
    <section className="admin-card"><div className="admin-section-heading"><h2>Friend accounts <small>{friends.length}</small></h2><button disabled={busy} onClick={()=>void load().catch(error=>setMessage(error.message))} aria-label="Refresh dashboard"><RefreshCw size={17}/></button></div>{!friends.length?<p>No individual friend accounts yet. Your existing guest login continues to work.</p>:<div className="admin-accounts">{friends.map(friend=><article key={friend.id}><div><strong>{friend.username}</strong><span>{friend.enabled?'Active':'Disabled'} · {friend.lastLogin?'Last sign-in '+new Date(friend.lastLogin).toLocaleDateString():'Has not signed in yet'}</span></div><div><button disabled={busy} onClick={()=>void mutate('/api/admin/account',{id:friend.id,enabled:!friend.enabled})}>{friend.enabled?'Disable':'Enable'}</button><button disabled={busy} onClick={()=>{setResetId(friend.id);setResetPassword('');}}>Reset password</button></div>{resetId===friend.id&&<form className="password-reset" onSubmit={async event=>{event.preventDefault();if(await mutate('/api/admin/account',{id:friend.id,password:resetPassword})){setResetId(null);setResetPassword('');}}}><label>New password<input type="password" required minLength={12} maxLength={200} value={resetPassword} onChange={e=>setResetPassword(e.target.value)} autoComplete="new-password"/></label><button disabled={busy}>Save password</button><button type="button" onClick={()=>setResetId(null)}>Cancel</button></form>}</article>)}</div>}</section>
    <section className="admin-card"><div className="admin-section-heading"><h2>Control Center · live now</h2><small>Auto-refresh · 15s · 90-second activity window</small></div><p>Live state is derived from authenticated telemetry heartbeats. No IP address, location, or browser fingerprint is required.</p><div className="service-connections"><span>Online accounts · {activeAccounts}</span><span>Watching now · {watchingAccounts}</span><span>Matches active · {matchesWatching}</span></div>{watchingAccounts>0&&<div className="admin-health">{Array.from(watchingByAccount.entries()).map(([account,event])=>{let detail:Record<string,unknown>={};try{detail=event.detail?JSON.parse(event.detail):{};}catch{}return <div key={account}><span>{label(account)}{typeof detail.matchId==="string"?` · ${detail.matchId}`:""}</span><time>{new Date(event.created).toLocaleTimeString()}</time><strong>Watching</strong></div>})}</div>}</section>
    <section className="admin-card"><div className="admin-section-heading"><h2>Control Center · recent activity</h2><small>{events.length} events · 7 days</small></div><p>Authenticated activity only. NINETY records internal account identity and match/player events; this view does not require browser fingerprinting.</p>{events.length?<div className="admin-health">{events.slice(0,50).map(row=>{let detail:Record<string,unknown>={};try{detail=row.detail?JSON.parse(row.detail):{};}catch{}return <div key={row.id}><span>{row.event.replaceAll("-", " ")}{typeof detail.home==="string"&&typeof detail.away==="string"?` · ${detail.home} vs ${detail.away}`:""}</span><time>{new Date(row.created).toLocaleString()}</time><strong>{row.account.startsWith("friend:")?"friend":row.account.split(":")[0]}</strong></div>})}</div>:<p>No telemetry yet. Activity will appear as authenticated users open and watch matches.</p>}</section>    <section className="admin-card"><h2>Service health · past 7 days</h2>{services&&<div className="service-connections"><span>Account storage · {services.accounts?"Connected":"Unavailable"}</span><span>Match data · {services.footballData?"Key configured":"Key not configured"}</span></div>}<p>Aggregate API failures, empty source responses and reported source retries. These do not measure video playback or prove a broadcast is broken.</p>{health.length?<div className="admin-health">{health.map(row=><div key={row.day+row.category}><span>{row.category.replaceAll('-',' ')}</span><time>{row.day} UTC</time><strong>{row.count}</strong></div>)}</div>:<p>No recorded service issues.</p>}</section></main>;
}
