import { NextResponse } from "next/server";
import type { StreamService } from "@/server/services/stream.service";
import { getStreamService } from "@/server/services/stream.service";
import { isSafeOpaqueId } from "@/server/http/input";
import { enforceRateLimit } from "@/server/http/rate-limit";
import { createRequestId, logServerEvent } from "@/server/observability/logger";
export const dynamic = "force-dynamic";
export function createStreamResolutionHandler(service: Pick<StreamService, "resolve">) { return async (matchId: string, streamId: string) => { if (!isSafeOpaqueId(matchId) || !isSafeOpaqueId(streamId)) return NextResponse.json({ error: { code: "INVALID_STREAM_REQUEST", message: "Stream request is invalid." } }, { status: 400, headers: { "Cache-Control": "no-store" } }); try { const result = await service.resolve(matchId, streamId); if (result.kind !== "ok") return NextResponse.json({ error: { code: result.kind === "match-not-found" ? "MATCH_NOT_FOUND" : "STREAM_NOT_FOUND", message: result.kind === "match-not-found" ? "Match unavailable." : "Stream unavailable." } }, { status: 404, headers: { "Cache-Control": "no-store" } }); return NextResponse.json(result.data, { headers: { "Cache-Control": "private, no-store", "Referrer-Policy": "no-referrer" } }); } catch { const requestId = createRequestId(); logServerEvent("stream_resolution_failed", requestId); return NextResponse.json({ error: { code: "STREAM_UNAVAILABLE", message: "Stream is temporarily unavailable." } }, { status: 503, headers: { "Cache-Control": "no-store", "x-request-id": requestId } }); } }; }
export async function GET(request: Request, { params }: RouteContext<"/api/football/match/[matchId]/streams/[streamId]">) { const limited = await enforceRateLimit(request, "playback"); if (limited) return limited; const { matchId, streamId } = await params; return createStreamResolutionHandler(getStreamService())(matchId, streamId); }
