"use client";

import { Bell, CalendarPlus, ChevronLeft, ChevronRight, CirclePlay, Download, ExternalLink, Grid2X2, List, LogOut, Shield, MoreHorizontal, Radio, Search, Share2, Signal, Star, Trophy, Users, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { isEffectivelyLive, isMatchEnded } from "./match-lifecycle";
import { highlightsSearchUrl } from "./highlights";
import { teamCatalog, teamGroups, type TeamGroup } from "./team-catalog";
import teamBadges from "./team-badges.json";
import { MatchTicker } from "./match-ticker";
import { accountStorage, initializeAccountStorage, accountRole } from "./account-storage";

type ApiSource={source:string;id:string};
type Match={id:string;sport:string;league:string;home:string;away:string;homeCode:string;awayCode:string;time:string;date?:number;live?:boolean;matchStatus?:string;popular?:boolean;colorA:string;colorB:string;apiSources?:ApiSource[];homeBadge?:string;awayBadge?:string};
type Filter="all"|"matchday"|"live"|"today"|"upcoming"|"favorites";
type ViewMode="cards"|"compact";
type TickerStatus="live"|"today"|"upcoming"|"ended";
type HeaderPanel="teams"|"reminders"|null;
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
const palettes=[["#776600","#006b91"],["#075b34","#082f21"],["#90142c","#8b7400"],["#174b7d","#192b4e"],["#703b0d","#71171b"],["#472b7c","#19545a"]] as const;
const teamColors=["#2f67b2","#9d2637","#047857","#7252aa","#b76b13","#087f8c","#b03078","#536a19"];

function normalizedTeam(value:string){return value.toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\b(fc|cf|afc|calcio|club)\b/g,"").replace(/[^a-z0-9]+/g," ").trim().replace(/^ac /,"").replace(/^ca /,"")}
function teamCode(name:string){const words=name.replace(/&/g," ").split(/\s+/).filter(word=>word&&!/^(fc|cf|afc|club|and|de)$/i.test(word));return (words.length>1?words.map(word=>word[0]).join(""):name.slice(0,3)).slice(0,3).toUpperCase()}
function teamColor(name:string){let hash=0;for(const character of name)hash=(hash*31+character.charCodeAt(0))|0;return teamColors[Math.abs(hash)%teamColors.length]}
function TeamMark({code,color,badge,name}:{code:string;color:string;badge?:string;name:string}){const markRef=useRef<HTMLSpanElement>(null),[remoteBadge,setRemoteBadge]=useState<string>(),[failedBadge,setFailedBadge]=useState<string>();const catalogBadge=teamBadges[name as keyof typeof teamBadges],activeBadge=[catalogBadge,badge,remoteBadge].find(url=>url&&url!==failedBadge),fallback=!activeBadge;useEffect(()=>{if(catalogBadge||badge||remoteBadge)return;let cancelled=false;const node=markRef.current,load=async()=>{const key="ninety-badge:"+normalizedTeam(name);try{const cached=window.sessionStorage.getItem(key);if(cached){if(!cancelled)setRemoteBadge(cached);return}const response=await fetch("/api/team-badge?name="+encodeURIComponent(name));if(!response.ok)return;const data=await response.json() as {badge?:string|null};if(data.badge){window.sessionStorage.setItem(key,data.badge);if(!cancelled)setRemoteBadge(data.badge)}}catch{}};if(!node){void load();return}const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){observer.disconnect();void load()}},{rootMargin:"180px"});observer.observe(node);return()=>{cancelled=true;observer.disconnect()}},[catalogBadge,badge,remoteBadge,name]);return <span ref={markRef} className={"team-mark "+(fallback?"fallback":"has-badge")} style={{"--team-color":color} as React.CSSProperties}><b className="team-initials">{(code||teamCode(name)).slice(0,2)}</b>{activeBadge&&<img src={activeBadge} alt={name+" badge"} loading="lazy" decoding="async" onError={()=>setFailedBadge(activeBadge)}/>}</span>}
function sameLocalDay(timestamp:number,now:number){const a=new Date(timestamp),b=new Date(now);return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function tomorrow(timestamp:number,now:number){const next=new Date(now);next.setDate(next.getDate()+1);return sameLocalDay(timestamp,next.getTime())}
function countdown(timestamp:number,now:number){const distance=timestamp-now;if(distance<=0)return "Starting soon";const minutes=Math.floor(distance/60000),days=Math.floor(minutes/1440),hours=Math.floor((minutes%1440)/60),mins=minutes%60;if(days>0)return days+"d "+hours+"h";if(hours>0)return hours+"h "+mins+"m";return Math.max(1,mins)+"m"}
function tickerStatus(match:Match,now:number):TickerStatus{if(isMatchEnded(match,now))return "ended";if(isEffectivelyLive(match,now))return "live";if(match.date&&sameLocalDay(match.date,now))return "today";return "upcoming"}
function leagueName(value:string){return !value||value.toLowerCase()==="football"?"Football":value.replace(/[-_]/g," ").replace(/\b\w/g,char=>char.toUpperCase())}
function matchHref(match:Match){return "/watch?match="+encodeURIComponent(match.id)}
const featuredTeams=new Map(Object.entries({"real madrid":900,"barcelona":900,"manchester city":850,"manchester united":850,"liverpool":850,"arsenal":820,"chelsea":780,"bayern munich":850,"paris saint-germain":820,"psg":820,"juventus":780,"inter milan":780,"ac milan":760,"england":800,"france":800,"spain":790,"germany":790,"italy":780,"portugal":780,"belgium":740,"brazil":850,"argentina":850,"netherlands":730,"croatia":700,"uruguay":730,"colombia":690,"mexico":680,"united states":680,"usa":680}));
function teamImportance(match:Match){return [match.home,match.away].reduce((score,name)=>score+(featuredTeams.get(name.toLocaleLowerCase())??0),0)}
function featuredScore(match:Match,now:number){if(isMatchEnded(match,now))return -Infinity;const live=isEffectivelyLive(match,now),hoursAway=match.date?Math.max(0,(match.date-now)/3600000):72;return (live?10000:0)+(match.popular?3500:0)+teamImportance(match)+Math.min(match.apiSources?.length??0,4)*25-Math.min(hoursAway,168)*8}

export default function Home(){
  const [matches,setMatches]=useState<Match[]>([]),[feedStatus,setFeedStatus]=useState<"loading"|"live"|"error">("loading");
  const [filter,setFilter]=useState<Filter>("all"),[league,setLeague]=useState("all"),[query,setQuery]=useState(""),[now,setNow]=useState(Date.now());
  const [scrolled,setScrolled]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[installPrompt,setInstallPrompt]=useState<InstallPrompt|null>(null),[viewMode,setViewMode]=useState<ViewMode>("cards");
  const [preferredTeams,setPreferredTeams]=useState<string[]>([]),[reminders,setReminders]=useState<string[]>([]),[panel,setPanel]=useState<HeaderPanel>(null),[teamSearch,setTeamSearch]=useState(""),[teamGroup,setTeamGroup]=useState<(typeof teamGroups)[number]>("All"),[spotlightIndex,setSpotlightIndex]=useState(0),[menuOpen,setMenuOpen]=useState(false);
  const searchRef=useRef<HTMLInputElement>(null);
  const [owner,setOwner]=useState(false),[syncStatus,setSyncStatus]=useState("synced");
  useEffect(()=>{const reload=()=>{setOwner(accountRole()==="owner");try{setFavorites(JSON.parse(accountStorage.getItem("ninety-favorites")||"[]"));setPreferredTeams(JSON.parse(accountStorage.getItem("ninety-teams")||"[]"));setReminders(JSON.parse(accountStorage.getItem("ninety-reminders")||"[]"));setViewMode(accountStorage.getItem("ninety-view")==="compact"?"compact":"cards");}catch{}};const sync=(event:Event)=>setSyncStatus((event as CustomEvent<string>).detail);window.addEventListener("ninety-preferences",reload);window.addEventListener("ninety-sync",sync);void initializeAccountStorage().then(reload).catch(()=>{});return()=>{window.removeEventListener("ninety-preferences",reload);window.removeEventListener("ninety-sync",sync);};},[]);
  const loadMatches=useCallback(async(silent=false)=>{if(!silent)setFeedStatus("loading");try{await initializeAccountStorage();const response=await fetch("/api/matches",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {matches?:Match[]};if(!Array.isArray(data.matches))throw new Error("Invalid match feed");setMatches(data.matches);setFeedStatus("live")}catch{setFeedStatus("error")}},[]);

  useEffect(()=>{void loadMatches();const refresh=window.setInterval(()=>void loadMatches(true),60000);const clock=window.setInterval(()=>setNow(Date.now()),30000);return()=>{window.clearInterval(refresh);window.clearInterval(clock)}},[loadMatches]);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
  useEffect(()=>{let cancelled=false;void initializeAccountStorage().then(()=>{if(cancelled)return;try{setFavorites(JSON.parse(accountStorage.getItem("ninety-favorites")||"[]"));setPreferredTeams(JSON.parse(accountStorage.getItem("ninety-teams")||"[]"));setReminders(JSON.parse(accountStorage.getItem("ninety-reminders")||"[]"))}catch{}}).catch(()=>{});const onInstall=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPrompt)};window.addEventListener("beforeinstallprompt",onInstall);return()=>{cancelled=true;window.removeEventListener("beforeinstallprompt",onInstall)}},[]);
  useEffect(()=>{let cancelled=false;void initializeAccountStorage().then(()=>{if(!cancelled)setViewMode(accountStorage.getItem("ninety-view")==="compact"?"compact":"cards")}).catch(()=>{});const focusSearch=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;if(event.key==="/"&&!target?.matches("input, textarea, [contenteditable=true]")){event.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",focusSearch);return()=>{cancelled=true;window.removeEventListener("keydown",focusSearch)}},[]);

  // Only prune against a successfully loaded feed, never the initial empty state or an outage.
  useEffect(()=>{
    if(feedStatus!=="live")return;
    const available=new Set(matches.map(match=>match.id));
    const reminderEligible=new Set(matches.filter(match=>!isMatchEnded(match,now)).map(match=>match.id));
    const prune=(current:string[],ids:Set<string>,key:string)=>{
      const next=current.filter(id=>ids.has(id));
      if(next.length===current.length)return current;
      try{accountStorage.setItem(key,JSON.stringify(next));}catch{}
      return next;
    };
    setFavorites(current=>prune(current,available,"ninety-favorites"));
    setReminders(current=>prune(current,reminderEligible,"ninety-reminders"));
    try{
      const notified=JSON.parse(accountStorage.getItem("ninety-notified")||"[]");
      if(Array.isArray(notified)){const next=notified.filter(id=>available.has(id));if(next.length!==notified.length)accountStorage.setItem("ninety-notified",JSON.stringify(next));}
    }catch{}
  },[matches,feedStatus,now]);

  const favoriteSet=useMemo(()=>new Set(favorites),[favorites]);
  const preferredSet=useMemo(()=>new Set(preferredTeams.map(normalizedTeam)),[preferredTeams]);
  const reminderSet=useMemo(()=>new Set(reminders),[reminders]);
  const isPreferred=(match:Match)=>preferredSet.has(normalizedTeam(match.home))||preferredSet.has(normalizedTeam(match.away));
  const toggleFavorite=(id:string)=>setFavorites(current=>{const next=current.includes(id)?current.filter(item=>item!==id):[...current,id];accountStorage.setItem("ninety-favorites",JSON.stringify(next));toast.success(next.includes(id)?"Match saved":"Removed from saved matches");return next});
  const togglePreferred=(team:string)=>setPreferredTeams(current=>{const key=normalizedTeam(team),exists=current.some(item=>normalizedTeam(item)===key),next=exists?current.filter(item=>normalizedTeam(item)!==key):[...current,team];accountStorage.setItem("ninety-teams",JSON.stringify(next));toast.success(exists?team+" removed":team+" added to My Teams");return next});
  const toggleReminder=async(match:Match)=>{if(!match.date||isMatchEnded(match,Date.now())){toast.error("Reminders are only available before kickoff");return}if(reminderSet.has(match.id)){const next=reminders.filter(id=>id!==match.id);setReminders(next);accountStorage.setItem("ninety-reminders",JSON.stringify(next));toast.success("Reminder removed");return}if("Notification" in window&&Notification.permission==="default")await Notification.requestPermission();const next=[...reminders,match.id];setReminders(next);accountStorage.setItem("ninety-reminders",JSON.stringify(next));toast.success("Kickoff reminder saved",{description:"We’ll alert you 10 minutes before kickoff while NINETY is open."})};
  const shareMatch=async(match:Match)=>{const url=new URL(matchHref(match),window.location.origin).toString(),title=`${match.home} vs ${match.away} | NINETY Live`;try{if(navigator.share)await navigator.share({title,url});else{await navigator.clipboard.writeText(url);toast.success("Match link copied")}}catch(error){if((error as Error).name!=="AbortError")toast.error("Could not share this match")}};
  const install=async()=>{if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==="accepted")toast.success("NINETY Live installed");setInstallPrompt(null)};
  const changeView=(next:ViewMode)=>{setViewMode(next);accountStorage.setItem("ninety-view",next)};
  const addToCalendar=(match:Match)=>{if(!match.date)return;const stamp=(value:number)=>new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const escape=(value:string)=>value.replace(/([,;\\])/g,"\\$1").replace(/\n/g,"\\n"),url=new URL(matchHref(match),window.location.origin).toString(),calendar=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//NINETY Live//Matchday//EN","BEGIN:VEVENT",`UID:${escape(match.id)}@ninety.live`,`DTSTAMP:${stamp(Date.now())}`,`DTSTART:${stamp(match.date)}`,`DTEND:${stamp(match.date+2*60*60*1000)}`,`SUMMARY:${escape(match.home+" vs "+match.away)}`,`DESCRIPTION:${escape("Follow this fixture on NINETY Live")}`,`URL:${url}`,"END:VEVENT","END:VCALENDAR"].join("\r\n"),href=URL.createObjectURL(new Blob([calendar],{type:"text/calendar;charset=utf-8"})),link=document.createElement("a");link.href=href;link.download=(match.home+"-vs-"+match.away).replace(/[^a-z0-9]+/gi,"-").toLocaleLowerCase()+".ics";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(href);toast.success("Calendar event downloaded")};
  const showSaved=()=>{setFilter("favorites");setPanel(null);window.setTimeout(()=>document.getElementById("matches")?.scrollIntoView({behavior:"smooth"}),0)};

  useEffect(()=>{if(!reminders.length)return;let notified:string[]=[];try{notified=JSON.parse(accountStorage.getItem("ninety-notified")||"[]")}catch{}const pending=matches.filter(match=>reminderSet.has(match.id)&&match.date&&match.date-now<=600000&&match.date-now>-300000&&!notified.includes(match.id));if(!pending.length)return;for(const match of pending){const title=`${match.home} vs ${match.away} starts soon`;toast.info(title,{description:"Kickoff is less than 10 minutes away."});if("Notification" in window&&Notification.permission==="granted")new Notification(title,{body:"Open NINETY Live to view the match.",icon:"/icon-192.png"})}const next=[...notified,...pending.map(match=>match.id)];accountStorage.setItem("ninety-notified",JSON.stringify(next))},[matches,now,reminders,reminderSet]);

  const counts=useMemo(()=>({all:matches.length,matchday:matches.filter(match=>preferredSet.has(normalizedTeam(match.home))||preferredSet.has(normalizedTeam(match.away))||favoriteSet.has(match.id)||reminderSet.has(match.id)).length,live:matches.filter(match=>isEffectivelyLive(match,now)).length,today:matches.filter(match=>match.date&&sameLocalDay(match.date,now)).length,upcoming:matches.filter(match=>!isEffectivelyLive(match,now)&&Boolean(match.date&&match.date>now)).length,favorites:matches.filter(match=>favoriteSet.has(match.id)).length}),[matches,now,favoriteSet,preferredSet,reminderSet]);
  const leagues=useMemo(()=>Array.from(new Set(matches.map(match=>match.league||"football"))).sort((a,b)=>leagueName(a).localeCompare(leagueName(b))),[matches]);
  const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase();return matches.filter(match=>{const matchesSearch=!term||(match.home+" "+match.away+" "+match.league).toLocaleLowerCase().includes(term);const matchesLeague=league==="all"||(match.league||"football")===league,personal=preferredSet.has(normalizedTeam(match.home))||preferredSet.has(normalizedTeam(match.away))||favoriteSet.has(match.id)||reminderSet.has(match.id);const matchesFilter=filter==="all"||filter==="matchday"&&personal||filter==="live"&&isEffectivelyLive(match,now)||filter==="today"&&Boolean(match.date&&sameLocalDay(match.date,now))||filter==="upcoming"&&Boolean(!isEffectivelyLive(match,now)&&match.date&&match.date>now)||filter==="favorites"&&favoriteSet.has(match.id);return matchesSearch&&matchesLeague&&matchesFilter}).sort((a,b)=>Number(favoriteSet.has(b.id))-Number(favoriteSet.has(a.id))||Number(isPreferred(b))-Number(isPreferred(a))||Number(isEffectivelyLive(b,now))-Number(isEffectivelyLive(a,now))||Number(isMatchEnded(a,now))-Number(isMatchEnded(b,now))||Number(Boolean(b.apiSources?.length))-Number(Boolean(a.apiSources?.length))||(a.date??0)-(b.date??0))},[matches,filter,league,query,now,favoriteSet,preferredSet,reminderSet]);
  const spotlights=useMemo(()=>{const ranked=[...matches].filter(match=>!isMatchEnded(match,now)).sort((a,b)=>featuredScore(b,now)-featuredScore(a,now)||(a.date??Number.MAX_SAFE_INTEGER)-(b.date??Number.MAX_SAFE_INTEGER));const important=ranked.filter(match=>{const importance=teamImportance(match);return isEffectivelyLive(match,now)||importance>=1300||Boolean(match.popular&&importance>=650)});return (important.length?important:ranked.slice(0,1)).slice(0,3)},[matches,now]);
  const activeSpotlight=spotlights[Math.min(spotlightIndex,Math.max(0,spotlights.length-1))];
  useEffect(()=>{if(spotlightIndex>=spotlights.length)setSpotlightIndex(0)},[spotlights.length,spotlightIndex]);
  useEffect(()=>{if(spotlights.length<2||menuOpen)return;const rotation=window.setInterval(()=>{if(!document.hidden)setSpotlightIndex(index=>(index+1)%spotlights.length)},6500);return()=>window.clearInterval(rotation)},[spotlights.length,menuOpen]);
  const groups=useMemo(()=>{const result=[{key:"live",title:"Live now",items:[] as Match[]},{key:"today",title:"Later today",items:[] as Match[]},{key:"tomorrow",title:"Tomorrow",items:[] as Match[]},{key:"upcoming",title:"Coming up",items:[] as Match[]},{key:"ended",title:"Recently finished",items:[] as Match[]}];for(const match of visible){if(isEffectivelyLive(match,now))result[0].items.push(match);else if(isMatchEnded(match,now))result[4].items.push(match);else if(match.date&&sameLocalDay(match.date,now))result[1].items.push(match);else if(match.date&&tomorrow(match.date,now))result[2].items.push(match);else result[3].items.push(match)}return result.filter(group=>group.items.length)},[visible,now]);
  const tickerMatches=useMemo(()=>matches.filter(match=>!isMatchEnded(match,now)).sort((a,b)=>{const priority:Record<TickerStatus,number>={live:0,today:1,upcoming:2,ended:3};return priority[tickerStatus(a,now)]-priority[tickerStatus(b,now)]||(a.date??0)-(b.date??0)}),[matches,now]);
  const teamOptions=useMemo(()=>{type TeamOption={name:string;code:string;color:string;badge?:string;group:TeamGroup};const feedTeams=new Map<string,TeamOption>();for(const match of matches){for(const team of [{name:match.home,code:match.homeCode,color:match.colorA,badge:match.homeBadge},{name:match.away,code:match.awayCode,color:match.colorB,badge:match.awayBadge}])feedTeams.set(normalizedTeam(team.name),{...team,group:"Other"})}const teams=new Map<string,TeamOption>();for(const team of teamCatalog){const live=feedTeams.get(normalizedTeam(team.name));teams.set(normalizedTeam(team.name),{name:team.name,code:live?.code||teamCode(team.name),color:live?.color||teamColor(team.name),badge:live?.badge,group:team.group})}for(const [key,team] of feedTeams)if(!teams.has(key))teams.set(key,team);const term=teamSearch.trim().toLocaleLowerCase();const groupOrder=new Map<TeamGroup,number>([["Premier League",0],["La Liga",1],["Bundesliga",2],["Serie A",3],["Countries",4],["Other",5]]);return [...teams.values()].filter(team=>(teamGroup==="All"||team.group===teamGroup)&&(!term||team.name.toLocaleLowerCase().includes(term))).sort((a,b)=>Number(preferredSet.has(normalizedTeam(b.name)))-Number(preferredSet.has(normalizedTeam(a.name)))||(groupOrder.get(a.group)??9)-(groupOrder.get(b.group)??9)||(featuredTeams.get(b.name.toLocaleLowerCase())??0)-(featuredTeams.get(a.name.toLocaleLowerCase())??0)||a.name.localeCompare(b.name))},[matches,teamSearch,teamGroup,preferredSet]);
  const reminderMatches=useMemo(()=>reminders.map(id=>matches.find(match=>match.id===id)).filter((match):match is Match=>Boolean(match&&!isMatchEnded(match,now))).sort((a,b)=>(a.date??0)-(b.date??0)),[reminders,matches,now]);
  const tickerGroup=(duplicate=false)=><div className="ticker-group" aria-hidden={duplicate||undefined}>{tickerMatches.map(match=>{const status=tickerStatus(match,now);return <a className={"ticker-item "+status} key={(duplicate?"duplicate-":"")+match.id} href={matchHref(match)} tabIndex={duplicate?-1:undefined}><small>{status.toUpperCase()}</small><b>{match.homeCode}</b><span>{match.home+" vs "+match.away}</span><time>{isEffectivelyLive(match,now)?"Now":match.time}</time></a>})}</div>;
  const moreActions=(match:Match,featured=false)=><DropdownMenu onOpenChange={featured?setMenuOpen:undefined}><DropdownMenuTrigger asChild><button aria-label={featured?"More featured match options":"More match options"} title="More options"><MoreHorizontal size={18}/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="match-actions-menu">{match.date&&match.date>now&&!isMatchEnded(match,now)&&<><DropdownMenuItem onSelect={()=>addToCalendar(match)}><CalendarPlus/>Add to calendar</DropdownMenuItem><DropdownMenuItem onSelect={()=>void toggleReminder(match)}><Bell/>{reminderSet.has(match.id)?"Remove reminder":"Set reminder"}</DropdownMenuItem></>}<DropdownMenuItem onSelect={()=>void shareMatch(match)}><Share2/>Share match</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
  const renderCard=(match:Match,index:number)=>{const [colorA,colorB]=palettes[index%palettes.length],ended=isMatchEnded(match,now),live=isEffectivelyLive(match,now),saved=favoriteSet.has(match.id),preferred=isPreferred(match),status=ended?"ENDED":live?"LIVE":match.date&&match.date>now?"IN "+countdown(match.date,now):"UPCOMING";return <article className={"featured-match-card "+(ended?"ended ":"")+(preferred?"preferred":"")} key={match.id} onPointerMove={event=>{const rect=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty("--spot-x",event.clientX-rect.left+"px");event.currentTarget.style.setProperty("--spot-y",event.clientY-rect.top+"px")}} style={{"--card-a":colorA,"--card-b":colorB,"--delay":Math.min(index,8)*45+"ms"} as React.CSSProperties}>
    <a className="card-hit-area" href={matchHref(match)} aria-label={`Open ${match.home} versus ${match.away}`}><span className="sr-only">Open match</span></a><div className="card-quick-actions"><button className={saved?"active":""} onClick={()=>toggleFavorite(match.id)} aria-label={saved?"Remove saved match":"Save match"}><Star size={16} fill={saved?"currentColor":"none"}/></button><button onClick={()=>void shareMatch(match)} aria-label={`Share ${match.home} versus ${match.away}`}><Share2 size={16}/></button>{moreActions(match)}</div>
    <div className="featured-match-art"><span className={live?"featured-state live":"featured-state"}>{status}</span><div className="featured-clubs"><TeamMark code={match.homeCode} color={match.colorA} badge={match.homeBadge} name={match.home}/><strong>VS</strong><TeamMark code={match.awayCode} color={match.colorB} badge={match.awayBadge} name={match.away}/></div></div>
    <div className="featured-match-info"><div className="league-pill"><Trophy size={12}/>{leagueName(match.league)}{preferred&&<span className="your-team">MY TEAM</span>}</div><h2>{match.home} <span>vs.</span> {match.away}</h2><div className="match-meta"><span>{match.date?new Date(match.date).toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"}):leagueName(match.league)}</span><b className={live?"is-live":""}>{ended?"Broadcast ended":live?<><i/> Watch live</>:match.date?new Date(match.date).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}):match.time}</b></div><div className="match-card-bottom"><span><Signal size={13}/>{ended?"Broadcast ended":live?match.apiSources?.length?"Broadcast listed":"Checking broadcast":match.apiSources?.length?"Broadcast expected":"Awaiting broadcast"}</span>{ended?<a className="featured-cta highlights-card-link" href={highlightsSearchUrl(match)} target="_blank" rel="noopener noreferrer" aria-label={`Find ${match.home} versus ${match.away} highlights on YouTube`}>Find highlights<ExternalLink size={15}/></a>:<span className="featured-cta">{live?"Watch now":"View match"}<CirclePlay size={15}/></span>}</div></div>
  </article>};

  return <main><header className={"site-header catalog-header "+(scrolled?"compact":"")}><a className="brand home-brand" href="#top" aria-label="NINETY Live home"><img className="brand-mark" src="/ninety-mark.svg" alt="" aria-hidden="true"/><span className="brand-stack"><span className="brand-title-row"><strong>NINETY</strong><em>LIVE</em></span><small><i/>LIVE</small></span></a><nav className="header-hub" aria-label="Personal match tools"><button onClick={()=>setPanel("teams")}><Users size={16}/><span>My Teams</span>{preferredTeams.length>0&&<b>{preferredTeams.length}</b>}</button><button className={filter==="favorites"?"active":""} onClick={showSaved}><Star size={16}/><span>Saved</span>{favorites.length>0&&<b>{favorites.length}</b>}</button><button onClick={()=>setPanel("reminders")}><Bell size={16}/><span>Reminders</span>{reminders.length>0&&<b>{reminders.length}</b>}</button>{owner&&<button onClick={()=>window.location.assign("/admin")} aria-label="Open owner Control Center" title="Owner Control Center"><Shield size={16}/><span>Control Center</span></button>}</nav><div className="header-end"><form className="signout-form" action="/auth/logout" method="post"><button className="signout-button" type="submit" aria-label="Sign out" title="Sign out"><LogOut size={18} aria-hidden="true"/><span>Sign out</span></button></form>{installPrompt&&<button className="install-app" onClick={()=>void install()}><Download size={16}/><span>Install app</span></button>}</div></header>
    <section className="ticker" aria-label="Scrolling live and upcoming matches"><a className="ticker-summary" href="#matches" onClick={()=>setFilter("all")}><Radio size={15}/><span><small>ACTIVE</small><strong>{tickerMatches.length} MATCHES</strong></span></a><MatchTicker>{tickerGroup()}{tickerGroup(true)}</MatchTicker></section>
    <div className="page-wrap catalog-page" id="top"><section className="match-catalog" id="matches">
      <div className="catalog-tools discovery-bar"><label className="match-search"><Search size={18}/><input ref={searchRef} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search teams or leagues" aria-label="Search teams or leagues"/>{query?<button onClick={()=>setQuery("")} aria-label="Clear search"><X size={16}/></button>:<kbd>/</kbd>}</label><div className="catalog-tabs" role="tablist" aria-label="Match filters">{(["all","matchday","live","today","upcoming","favorites"] as Filter[]).map(item=><button key={item} role="tab" aria-selected={filter===item} className={filter===item?"active":""} onClick={()=>setFilter(item)}><span>{item==="all"?"All":item==="matchday"?"My Matchday":item[0].toUpperCase()+item.slice(1)}</span><b>{counts[item]}</b></button>)}</div><div className="display-controls"><div className="view-switch" role="group" aria-label="Match view"><button className={viewMode==="cards"?"active":""} onClick={()=>changeView("cards")} aria-label="Card view" aria-pressed={viewMode==="cards"}><Grid2X2 size={16}/></button><button className={viewMode==="compact"?"active":""} onClick={()=>changeView("compact")} aria-label="Compact view" aria-pressed={viewMode==="compact"}><List size={17}/></button></div></div></div>
      {(query||filter!=="all"||league!=="all")&&<div className="active-filter-reset"><button onClick={()=>{setQuery("");setFilter("all");setLeague("all")}}>Clear filters <X size={14}/></button></div>}
      {leagues.length>1&&<div className="league-filters" aria-label="League filters"><button className={league==="all"?"active":""} onClick={()=>setLeague("all")}>All leagues</button>{leagues.map(item=><button key={item} className={league===item?"active":""} onClick={()=>setLeague(item)}><Trophy size={12}/>{leagueName(item)}</button>)}</div>}
      {activeSpotlight&&filter==="all"&&!query&&league==="all"&&<section className="spotlight-section"><div className="spotlight-heading"><h2>Featured fixtures</h2></div><article key={activeSpotlight.id} className="match-spotlight" style={{"--spot-a":activeSpotlight.colorA,"--spot-b":activeSpotlight.colorB} as React.CSSProperties}><div className="spotlight-copy"><span>{isEffectivelyLive(activeSpotlight,now)?"LIVE NOW":"FEATURED MATCH"}</span><h2>{activeSpotlight.home} <i>vs.</i> {activeSpotlight.away}</h2><p>{leagueName(activeSpotlight.league)} · {activeSpotlight.date?new Date(activeSpotlight.date).toLocaleString([], {weekday:"long",hour:"numeric",minute:"2-digit"}):activeSpotlight.time}</p><div><a href={matchHref(activeSpotlight)}>{isEffectivelyLive(activeSpotlight,now)?"Watch live":"View match"}<CirclePlay size={17}/></a><button className={favoriteSet.has(activeSpotlight.id)?"active":""} onClick={()=>toggleFavorite(activeSpotlight.id)} aria-label="Save featured match"><Star size={17} fill={favoriteSet.has(activeSpotlight.id)?"currentColor":"none"}/></button><button onClick={()=>void shareMatch(activeSpotlight)} aria-label="Share featured match"><Share2 size={17}/></button>{moreActions(activeSpotlight,true)}</div></div><div className="spotlight-clubs"><TeamMark code={activeSpotlight.homeCode} color={activeSpotlight.colorA} badge={activeSpotlight.homeBadge} name={activeSpotlight.home}/><strong>VS</strong><TeamMark code={activeSpotlight.awayCode} color={activeSpotlight.colorB} badge={activeSpotlight.awayBadge} name={activeSpotlight.away}/></div>{spotlights.length>1&&<div className="spotlight-arrows"><button onClick={()=>setSpotlightIndex(index=>(index-1+spotlights.length)%spotlights.length)} aria-label="Previous featured match"><ChevronLeft size={19}/></button><span>{spotlightIndex+1} / {spotlights.length}</span><button onClick={()=>setSpotlightIndex(index=>(index+1)%spotlights.length)} aria-label="Next featured match"><ChevronRight size={19}/></button></div>}</article></section>}
      {feedStatus==="loading"?<div className="featured-match-grid" aria-label="Loading football matches">{[0,1,2].map(item=><div className="featured-match-card card-skeleton" key={item}><div/><span/><span/></div>)}</div>:visible.length?<div className="schedule-groups">{groups.map((group,groupIndex)=><section className="schedule-group" key={group.key}><div className="group-heading"><div><i className={group.key}/><h2>{group.title}</h2></div><span>{group.items.length} {group.items.length===1?"match":"matches"}</span></div><div className={"featured-match-grid "+(viewMode==="compact"?"compact":"")}>{group.items.map((match,index)=>renderCard(match,groupIndex*3+index))}</div></section>)}</div>:<div className="catalog-empty"><CirclePlay size={40}/><h2>{filter==="favorites"?"No saved matches yet":filter==="matchday"?"Nothing in My Matchday yet":query?"No matching football games":"No matches in this view"}</h2><p>{filter==="favorites"?"Tap the star on any match to keep it here.":filter==="matchday"?"Follow a team, save a match or set a reminder.":query?"Try another team or competition.":"Choose another filter or check again shortly."}</p>{filter==="matchday"&&<button className="choose-teams" onClick={()=>setPanel("teams")}><Users size={15}/>Choose teams</button>}{(query||filter!=="all"||league!=="all")&&<button onClick={()=>{setQuery("");setFilter("all");setLeague("all")}}>Show all matches</button>}</div>}
    </section></div>
    <Dialog open={panel!==null} onOpenChange={open=>{if(!open)setPanel(null)}}><DialogContent className="fan-dialog">{panel==="teams"?<><DialogHeader><DialogTitle>My Teams</DialogTitle><DialogDescription>Follow clubs and countries. Their fixtures will be ranked first on this device.</DialogDescription></DialogHeader><div className="team-picker-tools"><label className="team-picker-search"><Search size={17}/><input value={teamSearch} onChange={event=>setTeamSearch(event.target.value)} placeholder="Find any team" autoFocus/></label><div className="team-group-tabs" aria-label="Team categories">{teamGroups.map(group=><button key={group} className={teamGroup===group?"active":""} onClick={()=>setTeamGroup(group)}>{group}</button>)}</div></div><div className="team-picker">{teamOptions.map(team=>{const selected=preferredSet.has(normalizedTeam(team.name));return <button key={team.name} className={selected?"selected":""} onClick={()=>togglePreferred(team.name)}><TeamMark code={team.code} color={team.color} badge={team.badge} name={team.name}/><span className="team-picker-copy"><strong>{team.name}</strong><small>{team.group==="Other"?"Current fixtures":team.group}</small></span>{selected&&<Star size={15} fill="currentColor"/>}</button>})}</div></>:<><DialogHeader><DialogTitle>Kickoff reminders</DialogTitle><DialogDescription>Alerts appear 10 minutes before kickoff while NINETY is open.</DialogDescription></DialogHeader>{reminderMatches.length?<div className="reminder-list">{reminderMatches.map(match=><div key={match.id}><TeamMark code={match.homeCode} color={match.colorA} badge={match.homeBadge} name={match.home}/><span><strong>{match.home} vs {match.away}</strong><small>{match.date?new Date(match.date).toLocaleString([], {weekday:"short",hour:"numeric",minute:"2-digit"}):match.time}</small></span><button onClick={()=>void toggleReminder(match)} aria-label="Remove reminder"><X size={16}/></button></div>)}</div>:<div className="dialog-empty"><Bell size={30}/><strong>No reminders yet</strong><span>Use the bell on an upcoming match to add one.</span></div>}</>}</DialogContent></Dialog>
    {syncStatus==="offline"&&<p className="preference-sync-note" role="status">Preferences are saved on this device. Cloud sync is temporarily unavailable.</p>}<footer className="site-footer"><div className="footer-row"><a className="brand small" href="#top"><img className="brand-mark" src="/ninety-mark.svg" alt="" aria-hidden="true"/><strong>NINETY</strong><em>LIVE</em></a><span className="footer-copyright">© 2026 NINETY Live. All rights reserved.</span><span className="footer-note">Independent football viewing platform.</span></div></footer></main>
}
