"use client";

import { CirclePlay, Download, Radio, Search, Share2, Signal, Star, Trophy, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { isEffectivelyLive, isMatchEnded } from "./match-lifecycle";

type ApiSource={source:string;id:string};
type Match={id:string;sport:string;league:string;home:string;away:string;homeCode:string;awayCode:string;time:string;date?:number;live?:boolean;colorA:string;colorB:string;apiSources?:ApiSource[];homeBadge?:string;awayBadge?:string};
type Filter="all"|"live"|"today"|"upcoming"|"favorites";
type TickerStatus="live"|"today"|"upcoming"|"ended";
type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
const palettes=[["#776600","#006b91"],["#075b34","#082f21"],["#90142c","#8b7400"],["#174b7d","#192b4e"],["#703b0d","#71171b"],["#472b7c","#19545a"]] as const;

function TeamMark({code,color,badge,name}:{code:string;color:string;badge?:string;name:string}){return <span className="team-mark" style={{"--team-color":color} as React.CSSProperties}>{badge?<img src={badge} alt={name+" badge"} loading="lazy" decoding="async"/>:code.slice(0,2)}</span>}
function sameLocalDay(timestamp:number,now:number){const a=new Date(timestamp),b=new Date(now);return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function tomorrow(timestamp:number,now:number){const next=new Date(now);next.setDate(next.getDate()+1);return sameLocalDay(timestamp,next.getTime())}
function countdown(timestamp:number,now:number){const distance=timestamp-now;if(distance<=0)return "Starting soon";const minutes=Math.floor(distance/60000),days=Math.floor(minutes/1440),hours=Math.floor((minutes%1440)/60),mins=minutes%60;if(days>0)return days+"d "+hours+"h";if(hours>0)return hours+"h "+mins+"m";return Math.max(1,mins)+"m"}
function tickerStatus(match:Match,now:number):TickerStatus{if(isMatchEnded(match,now))return "ended";if(isEffectivelyLive(match,now))return "live";if(match.date&&sameLocalDay(match.date,now))return "today";return "upcoming"}
function leagueName(value:string){return !value||value.toLowerCase()==="football"?"Football":value.replace(/[-_]/g," ").replace(/\b\w/g,char=>char.toUpperCase())}
function matchHref(match:Match){return "/watch?match="+encodeURIComponent(match.id)}

export default function Home(){
  const [matches,setMatches]=useState<Match[]>([]),[feedStatus,setFeedStatus]=useState<"loading"|"live"|"error">("loading");
  const [filter,setFilter]=useState<Filter>("all"),[league,setLeague]=useState("all"),[query,setQuery]=useState(""),[now,setNow]=useState(Date.now());
  const [scrolled,setScrolled]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[installPrompt,setInstallPrompt]=useState<InstallPrompt|null>(null);
  const loadMatches=useCallback(async(silent=false)=>{if(!silent)setFeedStatus("loading");try{const response=await fetch("/api/matches",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {matches?:Match[]};setMatches(data.matches??[]);setFeedStatus("live")}catch{setFeedStatus("error")}},[]);
  useEffect(()=>{void loadMatches();const refresh=window.setInterval(()=>void loadMatches(true),60000);const clock=window.setInterval(()=>setNow(Date.now()),30000);return()=>{window.clearInterval(refresh);window.clearInterval(clock)}},[loadMatches]);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
  useEffect(()=>{try{setFavorites(JSON.parse(window.localStorage.getItem("ninety-favorites")||"[]"))}catch{}const onInstall=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPrompt)};window.addEventListener("beforeinstallprompt",onInstall);return()=>window.removeEventListener("beforeinstallprompt",onInstall)},[]);
  const favoriteSet=useMemo(()=>new Set(favorites),[favorites]);
  const toggleFavorite=(id:string)=>setFavorites(current=>{const next=current.includes(id)?current.filter(item=>item!==id):[...current,id];window.localStorage.setItem("ninety-favorites",JSON.stringify(next));toast.success(next.includes(id)?"Match saved":"Removed from saved matches");return next});
  const shareMatch=async(match:Match)=>{const url=new URL(matchHref(match),window.location.origin).toString(),title=`${match.home} vs ${match.away} | NINETY Live`;try{if(navigator.share)await navigator.share({title,url});else{await navigator.clipboard.writeText(url);toast.success("Match link copied")}}catch(error){if((error as Error).name!=="AbortError")toast.error("Could not share this match")}};
  const install=async()=>{if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==="accepted")toast.success("NINETY Live installed");setInstallPrompt(null)};
  const counts=useMemo(()=>({all:matches.length,live:matches.filter(match=>isEffectivelyLive(match,now)).length,today:matches.filter(match=>match.date&&sameLocalDay(match.date,now)).length,upcoming:matches.filter(match=>!isEffectivelyLive(match,now)&&Boolean(match.date&&match.date>now)).length,favorites:matches.filter(match=>favoriteSet.has(match.id)).length}),[matches,now,favoriteSet]);
  const leagues=useMemo(()=>Array.from(new Set(matches.map(match=>match.league||"football"))).sort((a,b)=>leagueName(a).localeCompare(leagueName(b))),[matches]);
  const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase();return matches.filter(match=>{const matchesSearch=!term||(match.home+" "+match.away+" "+match.league).toLocaleLowerCase().includes(term);const matchesLeague=league==="all"||(match.league||"football")===league;const matchesFilter=filter==="all"||filter==="live"&&isEffectivelyLive(match,now)||filter==="today"&&Boolean(match.date&&sameLocalDay(match.date,now))||filter==="upcoming"&&Boolean(!isEffectivelyLive(match,now)&&match.date&&match.date>now)||filter==="favorites"&&favoriteSet.has(match.id);return matchesSearch&&matchesLeague&&matchesFilter}).sort((a,b)=>Number(favoriteSet.has(b.id))-Number(favoriteSet.has(a.id))||Number(isEffectivelyLive(b,now))-Number(isEffectivelyLive(a,now))||Number(isMatchEnded(a,now))-Number(isMatchEnded(b,now))||Number(Boolean(b.apiSources?.length))-Number(Boolean(a.apiSources?.length))||(a.date??0)-(b.date??0))},[matches,filter,league,query,now,favoriteSet]);
  const spotlight=useMemo(()=>[...matches].sort((a,b)=>Number(isEffectivelyLive(b,now))-Number(isEffectivelyLive(a,now))||Number(isMatchEnded(a,now))-Number(isMatchEnded(b,now))||(a.date??Number.MAX_SAFE_INTEGER)-(b.date??Number.MAX_SAFE_INTEGER))[0],[matches,now]);
  const groups=useMemo(()=>{const result=[{key:"live",title:"Live now",items:[] as Match[]},{key:"today",title:"Later today",items:[] as Match[]},{key:"tomorrow",title:"Tomorrow",items:[] as Match[]},{key:"upcoming",title:"Coming up",items:[] as Match[]},{key:"ended",title:"Recently finished",items:[] as Match[]}];for(const match of visible){if(isEffectivelyLive(match,now))result[0].items.push(match);else if(isMatchEnded(match,now))result[4].items.push(match);else if(match.date&&sameLocalDay(match.date,now))result[1].items.push(match);else if(match.date&&tomorrow(match.date,now))result[2].items.push(match);else result[3].items.push(match)}return result.filter(group=>group.items.length)},[visible,now]);
  const tickerMatches=useMemo(()=>[...matches].sort((a,b)=>{const priority:Record<TickerStatus,number>={live:0,today:1,upcoming:2,ended:3};return priority[tickerStatus(a,now)]-priority[tickerStatus(b,now)]||(a.date??0)-(b.date??0)}),[matches,now]);
  const tickerGroup=(duplicate=false)=><div className="ticker-group" aria-hidden={duplicate||undefined}>{tickerMatches.map(match=>{const status=tickerStatus(match,now);return <a className={"ticker-item "+status} key={(duplicate?"duplicate-":"")+match.id} href={matchHref(match)} tabIndex={duplicate?-1:undefined}><small>{status.toUpperCase()}</small><b>{match.homeCode}</b><span>{match.home+" vs "+match.away}</span><time>{isEffectivelyLive(match,now)?"Now":match.time}</time></a>})}</div>;
  const renderCard=(match:Match,index:number)=>{const [colorA,colorB]=palettes[index%palettes.length],ended=isMatchEnded(match,now),live=isEffectivelyLive(match,now),saved=favoriteSet.has(match.id),status=ended?"ENDED":live?"LIVE":match.date&&match.date>now?"IN "+countdown(match.date,now):"UPCOMING";return <article className={"featured-match-card "+(ended?"ended":"")} key={match.id} onPointerMove={event=>{const rect=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty("--spot-x",event.clientX-rect.left+"px");event.currentTarget.style.setProperty("--spot-y",event.clientY-rect.top+"px")}} style={{"--card-a":colorA,"--card-b":colorB,"--delay":Math.min(index,8)*45+"ms"} as React.CSSProperties}>
    <a className="card-hit-area" href={matchHref(match)} aria-label={`Open ${match.home} versus ${match.away}`}><span className="sr-only">Open match</span></a><div className="card-quick-actions"><button className={saved?"active":""} onClick={()=>toggleFavorite(match.id)} aria-label={saved?"Remove saved match":"Save match"}><Star size={16} fill={saved?"currentColor":"none"}/></button><button onClick={()=>void shareMatch(match)} aria-label="Share match"><Share2 size={16}/></button></div>
    <div className="featured-match-art"><span className={live?"featured-state live":"featured-state"}>{status}</span><div className="featured-clubs"><TeamMark code={match.homeCode} color={match.colorA} badge={match.homeBadge} name={match.home}/><strong>VS</strong><TeamMark code={match.awayCode} color={match.colorB} badge={match.awayBadge} name={match.away}/></div></div>
    <div className="featured-match-info"><div className="league-pill"><Trophy size={12}/>{leagueName(match.league)}</div><h2>{match.home} <span>vs.</span> {match.away}</h2><div className="match-meta"><span>{match.date?new Date(match.date).toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"}):leagueName(match.league)}</span><b className={live?"is-live":""}>{ended?"Broadcast ended":live?<><i/> Watch live</>:match.date?new Date(match.date).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}):match.time}</b></div><div className="match-card-bottom"><span><Signal size={13}/>{ended?"Broadcast ended":match.apiSources?.length?(match.apiSources.length+" source"+(match.apiSources.length===1?"":"s")):"Awaiting source"}</span><span className="featured-cta">{live?"Watch now":"View match"}<CirclePlay size={15}/></span></div></div>
  </article>};

  return <main><header className={"site-header catalog-header "+(scrolled?"compact":"")}><a className="brand" href="#top" aria-label="NINETY Live home"><span>N</span><strong>NINETY</strong><em>LIVE</em></a><nav aria-label="Primary navigation"><a className="active" href="#matches">Matches</a></nav>{installPrompt&&<button className="install-app" onClick={()=>void install()}><Download size={16}/><span>Install app</span></button>}</header>
    <section className="ticker" aria-label="Scrolling match schedule"><a className="ticker-summary" href="#matches" onClick={()=>setFilter("all")}><Radio size={15}/><span><small>ALL</small><strong>{counts.all} MATCHES</strong></span></a><div className="ticker-window"><div className="ticker-marquee">{tickerGroup()}{tickerGroup(true)}</div></div></section>
    <div className="page-wrap catalog-page" id="top"><section className="match-catalog" id="matches"><div className="catalog-title"><div><span className="eyebrow"><i/> LIVE &amp; UPCOMING</span><h1>Football</h1><p>Choose a match and start watching.</p></div></div>
      <div className="catalog-tools"><div className="catalog-tabs" role="tablist" aria-label="Match filters">{(["all","live","today","upcoming","favorites"] as Filter[]).map(item=><button key={item} role="tab" aria-selected={filter===item} className={filter===item?"active":""} onClick={()=>setFilter(item)}><span>{item==="all"?"All":item[0].toUpperCase()+item.slice(1)}</span><b>{counts[item]}</b></button>)}</div><label className="match-search"><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search teams or leagues" aria-label="Search teams or leagues"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear search"><X size={16}/></button>}</label></div>
      {leagues.length>1&&<div className="league-filters" aria-label="League filters"><button className={league==="all"?"active":""} onClick={()=>setLeague("all")}>All leagues</button>{leagues.map(item=><button key={item} className={league===item?"active":""} onClick={()=>setLeague(item)}><Trophy size={12}/>{leagueName(item)}</button>)}</div>}
      {spotlight&&filter==="all"&&!query&&league==="all"&&<section className="match-spotlight" style={{"--spot-a":spotlight.colorA,"--spot-b":spotlight.colorB} as React.CSSProperties}><div className="spotlight-copy"><span>{isEffectivelyLive(spotlight,now)?"LIVE NOW":"FEATURED MATCH"}</span><h2>{spotlight.home} <i>vs.</i> {spotlight.away}</h2><p>{leagueName(spotlight.league)} · {spotlight.date?new Date(spotlight.date).toLocaleString([], {weekday:"long",hour:"numeric",minute:"2-digit"}):spotlight.time}</p><div><a href={matchHref(spotlight)}>{isEffectivelyLive(spotlight,now)?"Watch live":"View match"}<CirclePlay size={17}/></a><button onClick={()=>toggleFavorite(spotlight.id)} aria-label="Save featured match"><Star size={17} fill={favoriteSet.has(spotlight.id)?"currentColor":"none"}/></button><button onClick={()=>void shareMatch(spotlight)} aria-label="Share featured match"><Share2 size={17}/></button></div></div><div className="spotlight-clubs"><TeamMark code={spotlight.homeCode} color={spotlight.colorA} badge={spotlight.homeBadge} name={spotlight.home}/><strong>VS</strong><TeamMark code={spotlight.awayCode} color={spotlight.colorB} badge={spotlight.awayBadge} name={spotlight.away}/></div></section>}
      {feedStatus==="loading"?<div className="featured-match-grid" aria-label="Loading football matches">{[0,1,2].map(item=><div className="featured-match-card card-skeleton" key={item}><div/><span/><span/></div>)}</div>:visible.length?<div className="schedule-groups">{groups.map((group,groupIndex)=><section className="schedule-group" key={group.key}><div className="group-heading"><div><i className={group.key}/><h2>{group.title}</h2></div><span>{group.items.length} {group.items.length===1?"match":"matches"}</span></div><div className="featured-match-grid">{group.items.map((match,index)=>renderCard(match,groupIndex*3+index))}</div></section>)}</div>:<div className="catalog-empty"><CirclePlay size={40}/><h2>{filter==="favorites"?"No saved matches yet":query?"No matching football games":"No matches in this view"}</h2><p>{filter==="favorites"?"Tap the star on any match to keep it here.":query?"Try another team or competition.":"Choose another filter or check again shortly."}</p>{(query||filter!=="all"||league!=="all")&&<button onClick={()=>{setQuery("");setFilter("all");setLeague("all")}}>Show all matches</button>}</div>}
    </section></div><footer className="site-footer"><div className="footer-row"><div className="footer-identity"><a className="brand small" href="#top"><span>N</span><strong>NINETY</strong><em>LIVE</em></a><span>© 2026 NINETY Live. All rights reserved.</span></div><span>Independent football viewing platform.</span></div></footer></main>
}
