import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Radio, ShieldCheck } from "lucide-react";

import { orderedWorldCompetitions } from "@/domain/football/competition-order";
import { EmptyState, PageIntro } from "@/features/discovery/components/discovery-ui";
import { LeagueMark } from "@/features/football/components/league-mark";
import { getFootballService } from "@/server/services/football.service";

export const metadata: Metadata = { title: "Football Leagues | NINETY", description: "Discover football competitions represented on NINETY." };
export const dynamic = "force-dynamic";

export default async function LeaguesPage() {
  const competitions = orderedWorldCompetitions(await getFootballService().getCompetitions());
  const fixtures = competitions.reduce((total, competition) => total + competition.fixtureCount, 0);
  const live = competitions.reduce((total, competition) => total + competition.liveCount, 0);
  return <><main className="page-shell py-8 sm:py-10"><section className="mb-10 grid gap-6 rounded-[28px] border border-white/[.07] bg-[radial-gradient(circle_at_top_right,rgba(199,255,74,.10),transparent_34%)] p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-end"><PageIntro eyebrow="League intelligence" title="The world’s competitions" detail="Every represented league, ranked by what is live and available now."/><div className="grid grid-cols-2 gap-3"><div className="min-w-32 rounded-2xl border border-white/[.07] bg-black/20 p-4"><p className="text-2xl font-semibold">{fixtures}</p><p className="mt-1 text-xs text-[#858d96]">Fixtures indexed</p></div><div className="min-w-32 rounded-2xl border border-white/[.07] bg-black/20 p-4"><p className="flex items-center gap-2 text-2xl font-semibold">{live}<Radio size={16} className="text-[#ff4d5e]"/></p><p className="mt-1 text-xs text-[#858d96]">Live now</p></div></div></section>{competitions.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{competitions.map((competition) => <Link key={competition.id} href={`/league/${competition.slug}`} className="group relative overflow-hidden rounded-3xl border border-white/[.07] bg-[#111419] p-5 hover:border-white/15 sm:p-6"><div className="flex items-start gap-5"><LeagueMark slug={competition.slug} name={competition.name} size="medium" showFallbackLabel/><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[.15em] text-[var(--lime)]">{competition.region}</p><h2 className="mt-1 truncate text-xl font-semibold">{competition.name}</h2></div><ArrowUpRight size={18} className="text-[#626a73] transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-white"/></div><div className="mt-6 grid grid-cols-3 divide-x divide-white/[.07] border-t border-white/[.07] pt-4 text-center"><div><p className="font-mono text-lg font-semibold">{competition.fixtureCount}</p><p className="text-[10px] uppercase tracking-wider text-[#727a83]">Fixtures</p></div><div><p className={competition.liveCount ? "font-mono text-lg font-semibold text-[#ff5b68]" : "font-mono text-lg font-semibold"}>{competition.liveCount}</p><p className="text-[10px] uppercase tracking-wider text-[#727a83]">Live</p></div><div><p className="font-mono text-lg font-semibold">{competition.clubCount}</p><p className="text-[10px] uppercase tracking-wider text-[#727a83]">Clubs</p></div></div>{competition.slug === "football" && <p className="mt-4 flex items-center gap-2 text-xs text-[#858d96]"><ShieldCheck size={14}/>Provider-grouped fixtures awaiting explicit league metadata</p>}</Link>)}</div> : <EmptyState title="No competitions available" copy="Represented leagues will appear when fixtures are available."/>}</main></>;
}
