"use client";
import Link from "next/link";
import { motion } from "motion/react";
import { ArrowUpRight, Radio } from "lucide-react";
import type { FootballDashboardData } from "@/domain/football/types";
import { AppHeader } from "@/features/shell/app-header";
import { FavoriteMatches } from "@/features/personalization/components/favorite-matches";
import { LeagueMark } from "./league-mark";
import { LocalKickoff } from "./local-kickoff";
import { MatchCard } from "./match-card";
import { TeamCrest } from "./team-crest";

export function FootballDashboard({ data }: { data: FootballDashboardData }) {
  const featured = data.featured;
  return <div className="noise min-h-screen pb-24 lg:pb-0"><AppHeader/><main className="page-shell pt-6 sm:pt-8">
    {featured ? <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="relative min-h-[420px] overflow-hidden rounded-[28px] border border-white/[.08] bg-[#11151a] px-6 py-8 sm:px-10 lg:px-14" id="today"><div className="absolute inset-0 opacity-75" style={{ background: `radial-gradient(circle at 88% 18%, ${featured.home.colors[0]}55, transparent 32%), radial-gradient(circle at 60% 90%, ${featured.away.colors[0]}3d, transparent 35%)` }}/><div className="absolute inset-0 bg-gradient-to-r from-[#0c0f13] via-[#0c0f13]/75 to-transparent"/><div className="relative z-10 flex min-h-[355px] flex-col justify-between"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#c7ff4a]"><span className={`h-2 w-2 rounded-full bg-[#c7ff4a] ${featured.status === "LIVE" ? "animate-pulse" : ""}`}/> {featured.status === "LIVE" ? "Live now" : "Up next"}<span className="text-white/35">•</span>{featured.competition}</div><div className="max-w-2xl"><p className="mb-5 text-sm text-[#a7adb4]">{featured.stage} · <LocalKickoff kickoff={featured.kickoff}/></p><div className="flex items-center gap-4 sm:gap-7"><TeamCrest team={featured.home} size="large"/><span className="font-mono text-4xl font-semibold tracking-[-.08em] sm:text-6xl">{featured.homeScore != null && featured.awayScore != null ? `${featured.homeScore}–${featured.awayScore}` : "v"}</span><TeamCrest team={featured.away} size="large"/></div><h1 className="mt-6 text-2xl font-semibold tracking-[-.04em] sm:text-4xl">{featured.home.name} <span className="text-white/35">vs</span> {featured.away.name}</h1><Link href={`/watch/${encodeURIComponent(featured.id)}`} className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#c7ff4a] px-5 text-sm font-bold text-[#080a0d]"><Radio size={18}/>{featured.status === "LIVE" ? "Follow live" : "View match"}</Link></div></div></motion.section> : <section id="today" className="grid min-h-[340px] place-items-center rounded-[28px] border border-white/[.08] bg-[#11151a] px-6 text-center"><div><p className="text-2xl font-semibold">No fixtures on the board yet</p><p className="mt-2 text-sm text-[#8d949d]">Check back soon for the next football window.</p></div></section>}
    <section className="py-9" id="matches"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.16em] text-[#c7ff4a]">Matchday</p><h2 className="text-2xl font-semibold tracking-[-.04em] sm:text-3xl">Your football, today</h2></div><span className="shrink-0 text-sm text-[#9da3ab]">{data.today.length} fixtures</span></div>{data.today.length ? <div className="hide-scrollbar flex gap-4 overflow-x-auto pb-2">{data.today.map((match) => <MatchCard key={match.id} match={match}/>)}</div> : <div className="rounded-2xl border border-dashed border-white/10 px-6 py-10 text-center text-sm text-[#8d949d]">No matches scheduled today.</div>}</section>
    <FavoriteMatches matches={data.matches}/>
    {data.upcoming.length > 0 && <section className="border-t border-white/[.07] py-9"><div className="mb-5 flex items-end justify-between"><h2 className="text-2xl font-semibold tracking-[-.04em] sm:text-3xl">Coming up</h2><span className="text-sm text-[#9da3ab]">Next fixtures</span></div><div className="hide-scrollbar flex gap-4 overflow-x-auto pb-2">{data.upcoming.slice(0, 8).map((match) => <MatchCard key={match.id} match={match}/>)}</div></section>}
    {data.competitions.length > 0 && <section className="border-t border-white/[.07] py-9" id="competitions"><h2 className="mb-5 text-2xl font-semibold tracking-[-.04em] sm:text-3xl">Follow the world&apos;s game</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.competitions.map((competition) => <Link href={`/league/${competition.slug}`} key={competition.id} className="group flex min-h-24 items-center gap-4 rounded-2xl border border-white/[.07] bg-[#111419] p-4 hover:border-white/15"><LeagueMark slug={competition.slug} name={competition.name} size="medium" showFallbackLabel/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{competition.name}</p><p className="mt-1 text-xs text-[#8d949d]">{competition.region}</p></div><ArrowUpRight size={17} className="text-[#626a73] group-hover:text-white"/></Link>)}</div></section>}
  </main></div>;
}
