"use client";
import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { Bell, ChevronRight, CirclePlay, Compass, House, Radio, Search, Star } from "lucide-react";
import type { FootballDashboardData, Match, Team } from "@/domain/football/types";
import { getFootballDashboard } from "@/features/football/api/football-client";

function Crest({ team, large = false }: { team: Team; large?: boolean }) {
  return <div className={`grid shrink-0 place-items-center rounded-[30%] border border-white/15 font-black text-white shadow-xl ${large ? "h-20 w-20 text-xl sm:h-24 sm:w-24" : "h-10 w-10 text-[11px]"}`} style={{ background: `linear-gradient(145deg, ${team.colors[0]}, ${team.colors[1]})` }} aria-label={`${team.name} crest`}><span className="rounded bg-black/25 px-1.5 py-1 backdrop-blur">{team.shortName}</span></div>;
}

function MatchCard({ match }: { match: Match }) {
  const label = match.status === "LIVE" ? `${match.minute}′ • Live` : match.status === "FINISHED" ? "Full time" : new Date(match.kickoff).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  return <motion.article whileHover={{ y: -3 }} className="min-w-[285px] flex-1 rounded-2xl border border-white/[.07] bg-[#12151a] p-5 sm:min-w-[320px]">
    <div className="mb-5 flex items-center justify-between text-[11px] font-semibold uppercase tracking-[.14em] text-[#8d949d]"><span>{match.competition}</span><span className={match.status === "LIVE" ? "text-[#c7ff4a]" : ""}>{label}</span></div>
    {[match.home, match.away].map((team, i) => <div className="mt-3 flex items-center gap-3" key={team.id}><Crest team={team}/><span className="flex-1 text-[15px] font-semibold">{team.name}</span><span className="font-mono text-2xl font-semibold">{i ? match.awayScore ?? "–" : match.homeScore ?? "–"}</span></div>)}
  </motion.article>;
}

export function FootballDashboard() {
  const [data, setData] = useState<FootballDashboardData | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => { const controller = new AbortController(); getFootballDashboard(controller.signal).then(setData).catch((e) => { if (e?.name !== "AbortError") setError(true); }); return () => controller.abort(); }, []);
  if (error) return <main className="grid min-h-screen place-items-center px-6 text-center"><div><p className="mb-2 text-2xl font-semibold">We&apos;re off the pitch for a moment.</p><button onClick={() => location.reload()} className="text-[#c7ff4a]">Try again</button></div></main>;
  if (!data) return <div className="mx-auto min-h-screen max-w-[1500px] animate-pulse px-5 pt-24"><div className="h-[430px] rounded-3xl bg-white/[.05]" /></div>;
  const featured = data.featured;
  return <div className="noise min-h-screen pb-24 lg:pb-0">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[.07] bg-[#080a0d]/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-[1500px] items-center gap-8 px-5 sm:px-8"><a href="#" className="text-xl font-black tracking-[-.08em]">NINETY<span className="text-[#c7ff4a]">.</span></a><nav className="hidden items-center gap-7 text-sm font-medium text-[#8d949d] md:flex" aria-label="Primary"><a className="text-white" href="#today">Today</a><a href="#competitions">Competitions</a><a href="#matches">Highlights</a></nav><div className="ml-auto flex items-center gap-2"><button aria-label="Search" className="rounded-full p-2.5 text-[#8d949d]"><Search size={19}/></button><button aria-label="Notifications" className="rounded-full p-2.5 text-[#8d949d]"><Bell size={19}/></button><div className="ml-1 h-8 w-8 rounded-full bg-gradient-to-br from-[#c7ff4a] to-[#209e68]" /></div></div></header>
    <main className="mx-auto max-w-[1500px] px-5 pt-24 sm:px-8">
      <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="relative min-h-[440px] overflow-hidden rounded-[28px] border border-white/[.08] bg-[#11151a] px-6 py-8 sm:px-10 lg:px-14" id="today"><div className="absolute inset-0 opacity-75" style={{ background: `radial-gradient(circle at 88% 18%, ${featured.home.colors[0]}55, transparent 32%), radial-gradient(circle at 60% 90%, ${featured.away.colors[0]}3d, transparent 35%)` }}/><div className="absolute inset-0 bg-gradient-to-r from-[#0c0f13] via-[#0c0f13]/75 to-transparent"/><div className="relative z-10 flex min-h-[375px] flex-col justify-between"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#c7ff4a]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#c7ff4a]"/> Live now <span className="text-white/35">•</span> {featured.competition}</div><div className="max-w-2xl"><p className="mb-5 text-sm text-[#a7adb4]">{featured.stage} · Emirates Stadium</p><div className="flex items-center gap-4 sm:gap-7"><Crest team={featured.home} large/><span className="font-mono text-5xl font-semibold tracking-[-.08em] sm:text-7xl">{featured.homeScore}–{featured.awayScore}</span><Crest team={featured.away} large/></div><h1 className="mt-6 text-2xl font-semibold tracking-[-.04em] sm:text-4xl">{featured.home.name} <span className="text-white/35">vs</span> {featured.away.name}</h1><div className="mt-7 flex flex-wrap gap-3"><button className="flex items-center gap-2 rounded-full bg-[#c7ff4a] px-5 py-3 text-sm font-bold text-[#080a0d]"><CirclePlay size={18} fill="currentColor"/> Watch live</button><button className="rounded-full border border-white/15 bg-white/[.05] px-5 py-3 text-sm font-semibold">Match centre</button></div></div></div></motion.section>
      <section className="py-10" id="matches"><div className="mb-5 flex items-end justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.16em] text-[#c7ff4a]">Matchday</p><h2 className="text-2xl font-semibold tracking-[-.04em] sm:text-3xl">Your football, today</h2></div><button className="flex items-center gap-1 text-sm text-[#9da3ab]">All matches <ChevronRight size={16}/></button></div><div className="hide-scrollbar flex gap-4 overflow-x-auto pb-2">{data.matches.map((match) => <MatchCard key={match.id} match={match}/>)}</div></section>
      <section className="border-t border-white/[.07] py-10" id="competitions"><div className="mb-5 flex items-end justify-between"><h2 className="text-2xl font-semibold tracking-[-.04em] sm:text-3xl">Follow the world&apos;s game</h2><Star size={18} className="text-[#8d949d]"/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.competitions.map((c, i) => <motion.button initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} transition={{ delay: i * .05 }} key={c.id} className="group flex items-center gap-4 rounded-2xl border border-white/[.07] bg-[#111419] p-4 text-left"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/[.06] text-sm font-black text-[#c7ff4a]">{c.name.slice(0,2).toUpperCase()}</div><div className="flex-1"><p className="font-semibold">{c.name}</p><p className="mt-1 text-xs text-[#8d949d]">{c.region}</p></div><ChevronRight size={17} className="text-[#555b63]"/></motion.button>)}</div></section>
    </main>
    <nav className="fixed inset-x-3 bottom-3 z-50 flex justify-around rounded-2xl border border-white/10 bg-[#15191e]/95 p-2 shadow-2xl backdrop-blur-xl lg:hidden" aria-label="Mobile navigation">{[[House,"Today"],[Radio,"Live"],[Compass,"Explore"],[Star,"Following"]].map(([Icon,label]) => { const NavIcon = Icon as typeof House; return <a href="#today" key={String(label)} className={`flex min-w-16 flex-col items-center gap-1 rounded-xl p-2 text-[10px] ${label === "Today" ? "bg-white/[.07] text-[#c7ff4a]" : "text-[#8d949d]"}`}><NavIcon size={18}/>{String(label)}</a>})}</nav>
  </div>;
}
