"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Radio, RefreshCw } from "lucide-react";
import type { FootballDashboardData, Match } from "@/domain/football/types";
import { getFootballDashboard } from "@/features/football/api/football-client";
import { usePublishLiveStatus } from "@/features/football/hooks/use-live-status";
import { KickoffProximity } from "./kickoff-proximity";
import { LiveIndicator } from "./live-indicator";
import { MatchShelf } from "./match-shelf";
import { TeamCrest } from "./team-crest";

export function FootballDashboard({ data: initialData }: { data?: FootballDashboardData }) {
  const [data, setData] = useState(initialData); const [failed, setFailed] = useState(false);
  usePublishLiveStatus(data ? data.featured?.status === "LIVE" || data.live.length > 0 : undefined);
  const load = async (signal?: AbortSignal) => { try { setData(await getFootballDashboard(signal)); } catch (error) { if ((error as Error).name !== "AbortError") setFailed(true); } };
  useEffect(() => { if (initialData) return; const controller = new AbortController(); getFootballDashboard(controller.signal).then(setData).catch((error: Error) => { if (error.name !== "AbortError") setFailed(true); }); return () => controller.abort(); }, [initialData]);
  if (!data) return failed ? <LoadFailure retry={() => { setFailed(false); void load(); }}/> : <DashboardLoading/>;
  const hasLive = data.featured?.status === "LIVE" || data.live.length > 0;
  return <div className="noise min-h-screen pb-24 md:pb-0"><main className="page-shell py-5 sm:py-8"><div className="mb-5 flex items-end justify-between gap-4"><div><div className="mb-2">{hasLive ? <LiveIndicator/> : <p className="text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Starting soon</p>}</div><h1 className="text-3xl font-semibold tracking-[-.055em] sm:text-5xl">What can I watch now?</h1></div><Link href="/live" className="hidden min-h-11 items-center rounded-full border border-white/10 px-4 text-sm font-bold text-white sm:inline-flex">All live</Link></div>{data.featured && <FeaturedHero match={data.featured}/>} {data.live.length > 0 && <MatchShelf eyebrow="On air" title="Live now" matches={data.live} href="/live"/>}{data.competitionSections.map((section) => <MatchShelf key={section.competition.slug} title={section.competition.name} matches={section.matches} href={`/league/${section.competition.slug}`}/>)}{data.otherFootball.length > 0 && <MatchShelf title="Other football" matches={data.otherFootball} href="/matches" showCompetition={false}/>}</main></div>;
}

function FeaturedHero({ match }: { match: Match }) { const live = match.status === "LIVE"; return <section aria-label={live ? "Most watched live" : "Featured upcoming match"} className={`relative overflow-hidden rounded-[26px] border bg-[#11151a] p-6 shadow-[0_24px_80px_rgba(0,0,0,.38)] sm:p-9 ${live ? "border-[#ff5969]/25" : "border-[var(--lime)]/20"}`}><div className="absolute inset-0 opacity-70" style={{ background: `radial-gradient(circle at 92% 10%, ${match.home.colors[0]}55, transparent 38%),radial-gradient(circle at 65% 100%,${match.away.colors[0]}35,transparent 42%)` }}/><div className="relative">{live ? <LiveIndicator minute={match.minute}/> : <p className="text-xs font-black uppercase tracking-[.18em] text-[var(--lime)]">Up next</p>}<p className="mt-3 text-sm text-white/55">{match.competition} · {live ? match.stage : <KickoffProximity kickoff={match.kickoff}/>}</p><div className="mt-6 flex items-center gap-4 sm:gap-6"><TeamCrest team={match.home} size="large"/><span className="font-mono text-3xl font-bold sm:text-5xl">{match.homeScore != null ? `${match.homeScore}–${match.awayScore}` : "v"}</span><TeamCrest team={match.away} size="large"/></div><h2 className="mt-5 max-w-3xl text-2xl font-semibold tracking-[-.045em] sm:text-4xl">{match.home.name} <span className="text-white/35">vs</span> {match.away.name}</h2><Link href={`/watch/${encodeURIComponent(match.id)}`} aria-label={`${live ? "Watch" : "View"} ${match.home.name} versus ${match.away.name}${live ? " live" : ""}`} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-full bg-[var(--lime)] px-6 text-sm font-black text-[#080a0d]"><Radio size={18}/>{live ? "Watch Live" : "View Match"}</Link></div></section>; }
function DashboardLoading() { return <main className="page-shell py-6" aria-label="Loading live football"><div className="skeleton h-4 w-28 rounded"/><div className="skeleton mt-4 h-10 w-80 max-w-full rounded"/><div className="skeleton mt-6 aspect-[16/8] max-h-[390px] rounded-[26px]"/></main>; }
function LoadFailure({ retry }: { retry: () => void }) { return <main className="page-shell grid min-h-[65vh] place-items-center text-center"><div><h1 className="text-2xl font-semibold">Live football is temporarily unavailable</h1><button onClick={retry} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-black"><RefreshCw size={16}/>Try again</button></div></main>; }
